# 第 Q 批：游戏/电商/交通/安卓/金融（目标各 24）
BATCHQ = [
# games 12->24 (+12)
("ubisoft","Ubisoft","https://www.ubisoft.com","育碧游戏。","games",["游戏平台"],"法国","英文",False),
("ea","EA","https://www.ea.com","艺电游戏。","games",["游戏平台"],"美国","英文",False),
("blizzard","暴雪","https://www.blizzard.com","暴雪娱乐。","games",["游戏平台"],"美国","英文",False),
("nintendo","任天堂","https://www.nintendo.com","任天堂。","games",["游戏平台"],"日本","英文",False),
("playstation","PlayStation","https://www.playstation.com","索尼游戏。","games",["游戏平台"],"日本","英文",False),
("xbox","Xbox","https://www.xbox.com","微软游戏。","games",["游戏平台"],"美国","英文",False),
("humblebundle","Humble Bundle","https://www.humblebundle.com","慈善游戏包。","games",["游戏平台"],"美国","英文",False),
("fanatical","Fanatical","https://www.fanatical.com","游戏折扣。","games",["游戏平台"],"英国","英文",False),
("greenmangaming","Green Man Gaming","https://www.greenmangaming.com","游戏商店。","games",["游戏平台"],"英国","英文",False),
# shop 12->24 (+12)
("walmart","Walmart","https://www.walmart.com","沃尔玛。","shop",["综合电商"],"美国","英文",False),
("target","Target","https://www.target.com","塔吉特。","shop",["综合电商"],"美国","英文",False),
("bestbuy","Best Buy","https://www.bestbuy.com","百思买。","shop",["综合电商"],"美国","英文",False),
("costco","Costco","https://www.costco.com","好市多。","shop",["综合电商"],"美国","英文",False),
("ikea","IKEA","https://www.ikea.com","宜家。","shop",["综合电商"],"瑞典","英文",False),
("decathlon","迪卡侬","https://www.decathlon.com","运动用品。","shop",["综合电商"],"法国","英文",False),
("uniqlo","优衣库","https://www.uniqlo.com","服装。","shop",["综合电商"],"日本","英文",False),
("muji","无印良品","https://www.muji.com","日杂。","shop",["综合电商"],"日本","英文",False),
("dangdang","当当网","https://www.dangdang.com","图书电商。","shop",["综合电商"],"中国","中文",False),
# transport 12->24 (+12)
("planefinder","Plane Finder","https://planefinder.net","航班追踪。","transport",["航空公司"],"英国","英文",False),
("radarbox","RadarBox","https://www.radarbox.com","航班追踪。","transport",["航空公司"],"美国","英文",False),
("adsbexchange","ADS-B Exchange","https://www.adsbexchange.com","开源航班追踪。","transport",["航空公司"],"国际","英文",False),
("seatguru","SeatGuru","https://www.seatguru.com","座位图。","transport",["航空公司"],"美国","英文",False),
("skyscanner","Skyscanner","https://www.skyscanner.com","机票比价。","transport",["航空公司"],"英国","英文",False),
("kayak","KAYAK","https://www.kayak.com","旅行比价。","transport",["航空公司"],"美国","英文",False),
("expedia","Expedia","https://www.expedia.com","旅行预订。","transport",["航空公司"],"美国","英文",False),
("rome2rio","Rome2Rio","https://www.rome2rio.com","交通路线。","transport",["航空公司"],"澳大利亚","英文",False),
("omio","Omio","https://www.omio.com","欧洲交通。","transport",["航空公司"],"德国","英文",False),
("trainline","Trainline","https://www.thetrainline.com","火车票。","transport",["航空公司"],"英国","英文",False),
("amtrak","Amtrak","https://www.amtrak.com","美铁。","transport",["铁路"],"美国","英文",False),
# android 14->24 (+10)
("fossdroid","Fossdroid","https://fossdroid.com","开源安卓应用。","android",["APK","开源"],"国际","英文",False),
("izzyondroid","IzzyOnDroid","https://apt.izzysoft.de","F-Droid 仓库。","android",["APK","开源"],"德国","英文",False),
("guardianproject","Guardian Project","https://guardianproject.info","隐私应用。","android",["APK"],"美国","英文",False),
("newpipe","NewPipe","https://newpipe.net","开源 YouTube 客户端。","android",["APK","开源"],"国际","英文",False),
("libretube","LibreTube","https://libretube.dev","开源视频客户端。","android",["APK","开源"],"国际","英文",False),
("infinity","Infinity","https://github.com/Docile-Alligator/Infinity-For-Reddit","Reddit 客户端。","android",["APK","开源"],"国际","英文",False),
("tachiyomi","Tachiyomi","https://tachiyomi.org","漫画阅读器。","android",["APK","开源"],"国际","英文",False),
("kuroba","Kuroba","https://github.com/K1rakishou/Kuroba-Experimental","4chan 客户端。","android",["APK","开源"],"国际","英文",False),
# finance 14->24 (+10)
("marketwatch","MarketWatch","https://www.marketwatch.com","财经新闻。","finance",["股票"],"美国","英文",False),
("investing","Investing.com","https://www.investing.com","行情数据。","finance",["股票"],"塞浦路斯","英文",False),
("seekingalpha","Seeking Alpha","https://seekingalpha.com","投资分析。","finance",["股票"],"美国","英文",False),
("morningstar","Morningstar","https://www.morningstar.com","基金评级。","finance",["基金"],"美国","英文",False),
("zacks","Zacks","https://www.zacks.com","股票研究。","finance",["股票"],"美国","英文",False),
("fool","Motley Fool","https://www.fool.com","投资建议。","finance",["股票"],"美国","英文",False),
("bankrate","Bankrate","https://www.bankrate.com","利率比较。","finance",["基金"],"美国","英文",False),
("nerdwallet","NerdWallet","https://www.nerdwallet.com","理财。","finance",["基金"],"美国","英文",False),
("wise","Wise","https://wise.com","跨境汇款。","finance",["外汇"],"英国","英文",False),
("revolut","Revolut","https://www.revolut.com","数字银行。","finance",["外汇"],"英国","英文",False),
("chime","Chime","https://www.chime.com","数字银行。","finance",["支付"],"美国","英文",False),
("cashapp","Cash App","https://cash.app","支付应用。","finance",["支付"],"美国","英文",False),
("venmo","Venmo","https://venmo.com","社交支付。","finance",["支付"],"美国","英文",False),
("wechatpay","微信支付","https://pay.weixin.qq.com","微信支付。","finance",["支付"],"中国","中文",False),
("unionpay","银联","https://www.unionpay.com","银联。","finance",["支付"],"中国","中文",False),
("jd_pay","京东支付","https://pay.jd.com","京东支付。","finance",["支付"],"中国","中文",False),
("steamdb","SteamDB","https://steamdb.info","Steam 数据库。","games",["Steam"],"国际","英文",False),
("protondb","ProtonDB","https://www.protondb.com","Linux 游戏兼容。","games",["Steam"],"国际","英文",False),
]
