# 第 O 批：数据库/浏览器/学术/视频创作（目标各 24）
BATCHO = [
# database 10->24 (+14)
("cassandra","Cassandra","https://cassandra.apache.org","分布式 NoSQL。","database",["数据库"],"国际","英文",False),
("couchdb","CouchDB","https://couchdb.apache.org","文档数据库。","database",["数据库"],"国际","英文",False),
("neo4j","Neo4j","https://neo4j.com","图数据库。","database",["数据库"],"美国","英文",False),
("influxdb","InfluxDB","https://www.influxdata.com","时序数据库。","database",["数据库"],"美国","英文",False),
("clickhouse","ClickHouse","https://clickhouse.com","列式数据库。","database",["数据库"],"国际","英文",False),
("cockroachdb","CockroachDB","https://www.cockroachlabs.com","分布式 SQL。","database",["数据库"],"美国","英文",False),
("tidb","TiDB","https://www.pingcap.com","国产分布式数据库。","database",["数据库"],"中国","英文",False),
("oceanbase","OceanBase","https://www.oceanbase.com","蚂蚁分布式数据库。","database",["数据库"],"中国","中文",False),
("navicat","Navicat","https://www.navicat.com","数据库管理工具。","database",["数据库工具"],"香港","英文",False),
("datagrip","DataGrip","https://www.jetbrains.com/datagrip","JetBrains DB 工具。","database",["数据库工具"],"捷克","英文",False),
# browser 10->24 (+14)
("librewolf","LibreWolf","https://librewolf.net","隐私 Firefox 分支。","browser",["Firefox"],"国际","英文",False),
("waterfox","Waterfox","https://www.waterfox.net","Firefox 分支。","browser",["Firefox"],"英国","英文",False),
("pale_moon","Pale Moon","https://www.palemoon.org","经典浏览器。","browser",["Firefox"],"国际","英文",False),
("qutebrowser","qutebrowser","https://qutebrowser.org","键盘驱动浏览器。","browser",["Chromium"],"德国","英文",False),
("nyxt","Nyxt","https://nyxt.atlas.engineer","黑客浏览器。","browser",["Chromium"],"国际","英文",False),
("duckduckgo_browser","DuckDuckGo 浏览器","https://duckduckgo.com/app","隐私浏览器。","browser",["隐私浏览器"],"美国","英文",False),
("orion","Orion","https://browser.kagi.com","Kagi 浏览器。","browser",["Chromium"],"美国","英文",False),
("sigmaos","SigmaOS","https://sigmaos.com","新锐浏览器。","browser",["Chromium"],"英国","英文",False),
("min_browser","Min","https://minbrowser.org","极简浏览器。","browser",["Chromium"],"国际","英文",False),
# academic 11->24 (+13)
("biorxiv","bioRxiv","https://www.biorxiv.org","生物预印本。","academic",["论文平台"],"美国","英文",False),
("medrxiv","medRxiv","https://www.medrxiv.org","医学预印本。","academic",["论文平台"],"美国","英文",False),
("ssrn","SSRN","https://www.ssrn.com","社科预印本。","academic",["论文平台"],"美国","英文",False),
("osf","OSF","https://osf.io","开放科学框架。","academic",["论文平台"],"美国","英文",False),
("figshare","figshare","https://figshare.com","科研数据分享。","academic",["论文平台"],"英国","英文",False),
("zenodo","Zenodo","https://zenodo.org","开放研究仓库。","academic",["论文平台"],"瑞士","英文",False),
("openalex","OpenAlex","https://openalex.org","开放学术图谱。","academic",["学术搜索"],"国际","英文",False),
("lens","Lens.org","https://www.lens.org","专利学术搜索。","academic",["学术搜索"],"澳大利亚","英文",False),
("dimensions","Dimensions","https://www.dimensions.ai","科研分析。","academic",["学术搜索"],"英国","英文",False),
("scopus","Scopus","https://www.scopus.com","文摘数据库。","academic",["论文平台"],"荷兰","英文",False),
("wos","Web of Science","https://www.webofscience.com","引文数据库。","academic",["论文平台"],"美国","英文",False),
("dblp","DBLP","https://dblp.org","计算机文献。","academic",["论文平台"],"德国","英文",False),
# vcreate 11->24 (+13)
("kdenlive","Kdenlive","https://kdenlive.org","开源剪辑。","vcreate",["视频编辑","开源"],"国际","英文",False),
("shotcut","Shotcut","https://www.shotcut.org","开源剪辑。","vcreate",["视频编辑","开源"],"国际","英文",False),
("olive","Olive","https://www.olivevideoeditor.org","开源剪辑。","vcreate",["视频编辑","开源"],"国际","英文",False),
("pitivi","Pitivi","https://www.pitivi.org","开源剪辑。","vcreate",["视频编辑","开源"],"国际","英文",False),
("lightworks","Lightworks","https://lwks.com","专业剪辑。","vcreate",["视频编辑"],"英国","英文",False),
("hitfilm","HitFilm","https://fxhome.com","特效剪辑。","vcreate",["视频编辑"],"英国","英文",False),
("movavi","Movavi","https://www.movavi.com","易用剪辑。","vcreate",["视频编辑"],"塞浦路斯","英文",False),
("veed","VEED","https://www.veed.io","在线剪辑。","vcreate",["视频编辑"],"英国","英文",False),
("kapwing","Kapwing","https://www.kapwing.com","在线剪辑。","vcreate",["视频编辑"],"美国","英文",False),
("clipchamp","Clipchamp","https://clipchamp.com","微软在线剪辑。","vcreate",["视频编辑"],"美国","英文",False),
("duckdb","DuckDB","https://duckdb.org","分析型数据库。","database",["数据库"],"荷兰","英文",False),
("questdb","QuestDB","https://questdb.io","时序数据库。","database",["数据库"],"英国","英文",False),
("surrealdb","SurrealDB","https://surrealdb.com","多模数据库。","database",["数据库"],"英国","英文",False),
("ferretdb","FerretDB","https://www.ferretdb.com","MongoDB 替代。","database",["数据库","开源"],"美国","英文",False),
("mullvad_browser","Mullvad Browser","https://mullvad.net/browser","隐私浏览器。","browser",["隐私浏览器"],"瑞典","英文",False),
("ghostery","Ghostery","https://www.ghostery.com","隐私浏览器。","browser",["隐私浏览器"],"德国","英文",False),
("startpage_browser","Startpage","https://www.startpage.com","隐私搜索。","browser",["隐私浏览器"],"荷兰","英文",False),
("academia","Academia.edu","https://www.academia.edu","学术社交。","academic",["论文平台"],"美国","英文",False),
("mdpi","MDPI","https://www.mdpi.com","开放获取出版。","academic",["论文平台"],"瑞士","英文",False),
("frontiers","Frontiers","https://www.frontiersin.org","开放获取期刊。","academic",["论文平台"],"瑞士","英文",False),
]
