# 第 T 批：开发/站长工具（目标 dev 40/webmaster 45）
BATCHT = [
# dev 22->40 (+18)
("java","Java","https://www.java.com","编程语言。","dev",["编程语言"],"美国","英文",False),
("kotlin","Kotlin","https://kotlinlang.org","JVM 语言。","dev",["编程语言"],"捷克","英文",False),
("php","PHP","https://www.php.net","Web 语言。","dev",["编程语言"],"国际","英文",False),
("ruby","Ruby","https://www.ruby-lang.org","编程语言。","dev",["编程语言"],"日本","英文",False),
("csharp","C#","https://learn.microsoft.com/dotnet/csharp","微软语言。","dev",["编程语言"],"美国","英文",False),
("cpp","C++","https://isocpp.org","系统语言。","dev",["编程语言"],"国际","英文",False),
("nodejs","Node.js","https://nodejs.org","JS 运行时。","dev",["编程语言"],"国际","英文",False),
("django","Django","https://www.djangoproject.com","Python 框架。","dev",["开发框架"],"国际","英文",False),
("flask","Flask","https://flask.palletsprojects.com","Python 微框架。","dev",["开发框架"],"国际","英文",False),
("spring","Spring","https://spring.io","Java 框架。","dev",["开发框架"],"美国","英文",False),
("laravel","Laravel","https://laravel.com","PHP 框架。","dev",["开发框架"],"国际","英文",False),
("rails","Ruby on Rails","https://rubyonrails.org","Ruby 框架。","dev",["开发框架"],"国际","英文",False),
("angular","Angular","https://angular.dev","前端框架。","dev",["开发框架"],"美国","英文",False),
# webmaster 30->45 (+15)
("cloudways","Cloudways","https://www.cloudways.com","云主机。","webmaster",["主机与服务器"],"马耳他","英文",False),
("kinsta","Kinsta","https://kinsta.com","WP 主机。","webmaster",["主机与服务器"],"美国","英文",False),
("siteground","SiteGround","https://www.siteground.com","主机商。","webmaster",["主机与服务器"],"保加利亚","英文",False),
("bluehost","Bluehost","https://www.bluehost.com","主机商。","webmaster",["主机与服务器"],"美国","英文",False),
("hostgator","HostGator","https://www.hostgator.com","主机商。","webmaster",["主机与服务器"],"美国","英文",False),
("dreamhost","DreamHost","https://www.dreamhost.com","主机商。","webmaster",["主机与服务器"],"美国","英文",False),
("ovh","OVHcloud","https://www.ovhcloud.com","欧洲云。","webmaster",["主机与服务器"],"法国","英文",False),
("hetzner","Hetzner","https://www.hetzner.com","德国主机。","webmaster",["主机与服务器"],"德国","英文",False),
("contabo","Contabo","https://contabo.com","便宜 VPS。","webmaster",["主机与服务器"],"德国","英文",False),
("ramnode","RamNode","https://www.ramnode.com","VPS。","webmaster",["主机与服务器"],"美国","英文",False),
("buyvm","BuyVM","https://buyvm.net","VPS。","webmaster",["主机与服务器"],"美国","英文",False),
("racknerd","RackNerd","https://www.racknerd.com","便宜 VPS。","webmaster",["主机与服务器"],"美国","英文",False),
("greencloud","GreenCloud","https://greencloudvps.com","VPS。","webmaster",["主机与服务器"],"越南","英文",False),
("hosthatch","HostHatch","https://hosthatch.com","VPS。","webmaster",["主机与服务器"],"美国","英文",False),
("netcup","netcup","https://www.netcup.com","德国主机。","webmaster",["主机与服务器"],"德国","英文",False),
("svelte","Svelte","https://svelte.dev","前端框架。","dev",["开发框架"],"国际","英文",False),
("nuxt","Nuxt","https://nuxt.com","Vue 全栈。","dev",["开发框架"],"国际","英文",False),
("astro","Astro","https://astro.build","静态框架。","dev",["开发框架"],"美国","英文",False),
("remix","Remix","https://remix.run","React 框架。","dev",["开发框架"],"美国","英文",False),
("solidjs","SolidJS","https://www.solidjs.com","前端框架。","dev",["开发框架"],"国际","英文",False),
("qwik","Qwik","https://qwik.dev","前端框架。","dev",["开发框架"],"美国","英文",False),
("htmx","htmx","https://htmx.org","HTML 扩展。","dev",["开发框架"],"国际","英文",False),
("bootstrap","Bootstrap","https://getbootstrap.com","CSS 框架。","dev",["开发框架"],"国际","英文",False),
("mui","MUI","https://mui.com","React UI。","dev",["开发框架"],"国际","英文",False),
("antdesign","Ant Design","https://ant.design","React UI。","dev",["开发框架"],"中国","中文",False),
]
