# 第 G 批：薄弱分类补强 + 站长工具
BATCHG = [
# 港口/地址/国家/城市/机场补强
("porttechnology","Port Technology","https://www.porttechnology.org","港口技术资讯。","ports",["港口代码"],"英国","英文",False),
("worldportsource","World Port Source","https://www.worldportsource.com","世界港口名录。","ports",["港口代码"],"美国","英文",False),
("searates","SeaRates","https://www.searates.com","海运费率与港口查询。","ports",["航线资料"],"英国","英文",False),
("geonames_postal","GeoNames 邮编","https://www.geonames.org/postalcode-search.html","全球邮编查询。","address",["邮编规则"],"国际","英文",False),
("addressdoctor","AddressDoctor","https://www.addressdoctor.com","国际地址格式验证。","address",["地址格式"],"德国","英文",False),
("countrycode","CountryCode.org","https://countrycode.org","国际电话区号查询。","address",["电话格式"],"国际","英文",False),
("nationsonline","Nations Online","https://www.nationsonline.org","国家资料库。","countries",["国家资料"],"德国","英文",False),
("worldometers","Worldometer","https://www.worldometers.info","世界实时统计数据。","countries",["国家资料"],"美国","英文",False),
("indexmundi","IndexMundi","https://www.indexmundi.com","国家统计数据库。","countries",["国家资料"],"美国","英文",False),
("citypopulation","City Population","https://www.citypopulation.de","城市人口数据。","cities",["城市资料"],"德国","英文",False),
("world_airport_codes","World Airport Codes","https://www.world-airport-codes.com","机场代码查询。","airports",["IATA代码"],"英国","英文",False),
("flightstats","FlightStats","https://www.flightstats.com","航班机场数据。","airports",["机场信息"],"美国","英文",False),
("apple_support","Apple 支持","https://support.apple.com","苹果官方支持。","apple",["iOS","macOS"],"美国","中文",False),
("apple_developer","Apple Developer","https://developer.apple.com","苹果开发者中心。","apple",["iOS"],"美国","英文",False),
("macworld","Macworld","https://www.macworld.com","苹果生态媒体。","apple",["macOS"],"美国","英文",False),
("9to5mac","9to5Mac","https://9to5mac.com","苹果新闻社区。","apple",["iOS"],"美国","英文",False),
# 健康
("webmd","WebMD","https://www.webmd.com","健康资讯平台。","health",["医学资源"],"美国","英文",False),
("nih","美国国立卫生研究院","https://www.nih.gov","NIH 官方。","health",["医疗机构"],"美国","英文",False),
("who","世界卫生组织","https://www.who.int","WHO 官方。","health",["医疗机构"],"瑞士","多语言",False),
("nejm","新英格兰医学杂志","https://www.nejm.org","顶级医学期刊。","health",["医学资源"],"美国","英文",False),
("haodf","好大夫在线","https://www.haodf.com","在线问诊平台。","health",["医疗机构"],"中国","中文",False),
# 政府
("usa_gov","USA.gov","https://www.usa.gov","美国政府官网。","gov",["美国政府"],"美国","英文",False),
("europa","欧盟官网","https://european-union.europa.eu","欧盟官方。","gov",["欧盟机构"],"比利时","英文",False),
("gov_uk","英国政府","https://www.gov.uk","英国政府官网。","gov",["欧盟机构"],"英国","英文",False),
# 企业
("crunchbase","Crunchbase","https://www.crunchbase.com","创投企业数据库。","companies",["科技企业"],"美国","英文",False),
("qcc","企查查","https://www.qcc.com","企业信息查询。","companies",["科技企业"],"中国","中文",False),
("forbes","福布斯","https://www.forbes.com","商业媒体榜单。","companies",["世界500强"],"美国","英文",False),
# 站长工具
("godaddy","GoDaddy","https://www.godaddy.com","域名主机服务商。","webmaster",["域名注册"],"美国","英文",False),
("cloudflare_reg","Cloudflare Registrar","https://www.cloudflare.com/products/registrar","成本价域名注册。","webmaster",["域名注册"],"美国","英文",False),
("west263","西部数码","https://www.west.cn","国内域名主机商。","webmaster",["域名注册"],"中国","中文",False),
("dnspod","DNSPod","https://www.dnspod.cn","腾讯 DNS 解析。","webmaster",["域名注册"],"中国","中文",False),
("tencent_cloud","腾讯云","https://cloud.tencent.com","腾讯云服务。","webmaster",["主机与服务器"],"中国","中文",False),
("huawei_cloud","华为云","https://www.huaweicloud.com","华为云服务。","webmaster",["主机与服务器"],"中国","中文",False),
("bandwagonhost","搬瓦工","https://bandwagonhost.com","VPS 服务商。","webmaster",["主机与服务器"],"美国","中文",False),
("netlify","Netlify","https://www.netlify.com","静态网站托管。","webmaster",["主机与服务器"],"美国","英文",False),
("semrush","Semrush","https://www.semrush.com","SEO 营销工具。","webmaster",["SEO工具"],"美国","英文",False),
("moz","Moz","https://moz.com","SEO 工具社区。","webmaster",["SEO工具"],"美国","英文",False),
("baidu_tongji","百度统计","https://tongji.baidu.com","网站流量统计。","webmaster",["统计分析"],"中国","中文",False),
("cnzz","友盟+","https://www.umeng.com","移动统计分析。","webmaster",["统计分析"],"中国","中文",False),
("adsense","Google AdSense","https://www.google.com/adsense","谷歌广告联盟。","webmaster",["广告联盟"],"美国","英文",False),
("alimama","阿里妈妈","https://www.alimama.com","阿里广告联盟。","webmaster",["广告联盟"],"中国","中文",False),
("themeforest","ThemeForest","https://themeforest.net","网站模板市场。","webmaster",["建站模板"],"澳大利亚","英文",False),
("w3schools_templates","W3Schools 模板","https://www.w3schools.com/w3css/w3css_templates.asp","免费网页模板。","webmaster",["建站模板"],"挪威","英文",False),
("drupal","Drupal","https://www.drupal.org","开源 CMS。","webmaster",["CMS系统","开源"],"美国","英文",False),
("joomla","Joomla","https://www.joomla.org","开源 CMS。","webmaster",["CMS系统","开源"],"美国","英文",False),
("typecho","Typecho","https://typecho.org","轻量博客 CMS。","webmaster",["CMS系统","开源"],"中国","中文",False),
("zerossl","ZeroSSL","https://zerossl.com","免费 SSL 证书。","webmaster",["SSL证书"],"瑞士","英文",False),
]
