# 第 C 批：设计/视频创作/办公/实用工具
BATCHC = [
("dribbble","Dribbble","https://dribbble.com","设计师作品分享社区。","design",["UI设计"],"美国","英文",False),
("behance","Behance","https://www.behance.net","Adobe 旗下创意作品平台。","design",["UI设计"],"美国","英文",False),
("pinterest","Pinterest","https://www.pinterest.com","灵感图片收藏社区。","design",["图片素材"],"美国","英文",False),
("pexels","Pexels","https://www.pexels.com","免费图片视频素材。","design",["图片素材"],"德国","英文",False),
("pixabay","Pixabay","https://pixabay.com","免费正版图片素材。","design",["图片素材"],"德国","英文",False),
("flaticon","Flaticon","https://www.flaticon.com","免费图标资源库。","design",["图标"],"西班牙","英文",False),
("iconfinder","Iconfinder","https://www.iconfinder.com","图标搜索引擎。","design",["图标"],"丹麦","英文",False),
("googlefonts","Google Fonts","https://fonts.google.com","免费开源字体库。","design",["字体"],"美国","英文",False),
("dafont","DaFont","https://www.dafont.com","免费字体下载。","design",["字体"],"法国","英文",False),
("coolors","Coolors","https://coolors.co","配色方案生成器。","design",["UI设计"],"国际","英文",False),
("blender","Blender","https://www.blender.org","免费开源 3D 创作套件。","design",["3D模型","开源"],"荷兰","英文",False),
("sketchfab","Sketchfab","https://sketchfab.com","3D 模型分享平台。","design",["3D模型"],"美国","英文",False),
("remove_bg","remove.bg","https://www.remove.bg","AI 一键抠图。","design",["图片工具"],"奥地利","英文",False),
("tinypng","TinyPNG","https://tinypng.com","在线图片压缩。","design",["图片工具"],"荷兰","英文",False),
("premiere","Adobe Premiere","https://www.adobe.com/products/premiere.html","专业视频剪辑软件。","vcreate",["视频编辑"],"美国","英文",False),
("finalcut","Final Cut Pro","https://www.apple.com/final-cut-pro","苹果专业剪辑软件。","vcreate",["视频编辑"],"美国","英文",False),
("filmora","万兴喵影","https://filmora.wondershare.cn","易用的视频剪辑软件。","vcreate",["视频编辑"],"中国","中文",False),
("bcut","必剪","https://bcut.bilibili.com","B站出品的视频剪辑工具。","vcreate",["视频编辑"],"中国","中文",False),
("aegisub","Aegisub","https://aegisub.org","开源字幕制作软件。","vcreate",["字幕工具","开源"],"国际","英文",False),
("arc_time","Arctime","https://arctime.org","免费字幕制作软件。","vcreate",["字幕工具"],"中国","中文",False),
("blender_video","OpenShot","https://www.openshot.org","免费开源视频编辑器。","vcreate",["视频编辑","开源"],"美国","英文",False),
("streamlabs","Streamlabs","https://streamlabs.com","直播工具套件。","vcreate",["直播工具"],"美国","英文",False),
("ms_office","Microsoft 365","https://www.microsoft.com/microsoft-365","微软办公套件。","office",["Office"],"美国","英文",False),
("wps","WPS Office","https://www.wps.cn","金山办公套件。","office",["Office"],"中国","中文",False),
("google_docs","Google Docs","https://docs.google.com","Google 在线文档。","office",["Office"],"美国","英文",False),
("libreoffice","LibreOffice","https://www.libreoffice.org","免费开源办公套件。","office",["Office","开源"],"德国","英文",False),
("smallpdf","Smallpdf","https://smallpdf.com","在线 PDF 工具。","office",["PDF"],"瑞士","英文",False),
("xmind","XMind","https://www.xmind.cn","思维导图软件。","office",["思维导图"],"中国","中文",False),
("processon","ProcessOn","https://www.processon.com","在线流程图协作。","office",["流程图"],"中国","中文",False),
("regexr","RegExr","https://regexr.com","正则表达式学习测试。","utils",["开发工具"],"美国","英文",False),
("caniuse","Can I use","https://caniuse.com","浏览器兼容性查询。","utils",["开发工具"],"国际","英文",False),
("qr_code","草料二维码","https://cli.im","二维码生成美化。","utils",["二维码"],"中国","中文",False),
("convertio","Convertio","https://convertio.co","在线文件格式转换。","utils",["文件转换"],"国际","英文",False),
("temp_mail","Temp Mail","https://temp-mail.org","临时邮箱服务。","utils",["临时邮箱"],"国际","英文",False),
("10minutemail","10 Minute Mail","https://10minutemail.com","10 分钟临时邮箱。","utils",["临时邮箱"],"美国","英文",False),
("wolfram","WolframAlpha","https://www.wolframalpha.com","计算知识引擎。","utils",["计算工具"],"美国","英文",False),
("desmos","Desmos","https://www.desmos.com","在线图形计算器。","utils",["计算工具"],"美国","英文",False),
("earthnull","Earth Nullschool","https://earth.nullschool.net","全球气象可视化。","utils",["数据可视化"],"国际","英文",False),
("screenshot","Screenshot Machine","https://www.screenshotmachine.com","网站截图 API。","utils",["开发工具"],"国际","英文",False),
("downforeveryone","Down For Everyone","https://downforeveryoneorjustme.com","网站宕机检测。","utils",["网络工具"],"美国","英文",False),
]
