# 第 K 批：城市/机场/港口/地址/国家（目标各 15）
BATCHK = [
# cities 3->15 (+12)
("wikivoyage","维基导游","https://www.wikivoyage.org","自由旅行指南。","cities",["城市资料"],"国际","多语言",False),
("lonelyplanet","Lonely Planet","https://www.lonelyplanet.com","旅行指南。","cities",["城市资料"],"美国","英文",False),
("timeout","Time Out","https://www.timeout.com","城市生活指南。","cities",["城市资料"],"英国","英文",False),
("worldcities","World Cities","https://www.worldcitiescultureforum.com","世界城市文化论坛。","cities",["城市资料"],"英国","英文",False),
("citymayors","City Mayors","https://www.citymayors.com","城市统计。","cities",["城市资料"],"英国","英文",False),
("demographia","Demographia","https://www.demographia.com","城市人口研究。","cities",["城市资料"],"美国","英文",False),
("skyscraperpage","SkyscraperPage","https://skyscraperpage.com","摩天大楼数据库。","cities",["城市资料"],"加拿大","英文",False),
("emporis","Emporis","https://www.emporis.com","建筑数据库。","cities",["城市资料"],"德国","英文",False),
("flickr_commons","Flickr 城市","https://www.flickr.com","城市照片社区。","cities",["城市资料"],"美国","英文",False),
("opentripmap","OpenTripMap","https://opentripmap.com","开放旅游地图。","cities",["景点"],"国际","英文",False),
("atlasobscura","Atlas Obscura","https://www.atlasobscura.com","奇观景点指南。","cities",["景点"],"美国","英文",False),
# airports 4->15 (+11)
("flightconnections","FlightConnections","https://www.flightconnections.com","航线图查询。","airports",["机场信息"],"国际","英文",False),
("airportia","Airportia","https://www.airportia.com","机场信息。","airports",["机场信息"],"国际","英文",False),
("sleepinginairports","Sleeping in Airports","https://www.sleepinginairports.net","机场过夜指南。","airports",["机场信息"],"国际","英文",False),
("loungebuddy","LoungeBuddy","https://www.loungebuddy.com","机场贵宾厅。","airports",["机场信息"],"美国","英文",False),
("prioritypass","Priority Pass","https://www.prioritypass.com","贵宾厅会员。","airports",["机场信息"],"英国","英文",False),
("icao","ICAO","https://www.icao.int","国际民航组织。","airports",["ICAO代码"],"加拿大","英文",False),
("airnav","AirNav","https://www.airnav.com","机场数据库。","airports",["机场信息"],"美国","英文",False),
("airportcodes","Airport Codes","https://www.airportcodes.org","机场代码。","airports",["IATA代码"],"国际","英文",False),
("aviationweather","Aviation Weather","https://www.aviationweather.gov","航空气象。","airports",["机场信息"],"美国","英文",False),
("liveatc","LiveATC","https://www.liveatc.net","机场通话直播。","airports",["机场信息"],"美国","英文",False),
("flightdiary","FlightDiary","https://flightdiary.net","飞行记录。","airports",["机场信息"],"国际","英文",False),
# ports 4->15 (+11)
("portofrotterdam","鹿特丹港","https://www.portofrotterdam.com","欧洲最大港。","ports",["港口代码"],"荷兰","英文",False),
("portofsingapore","新加坡港","https://www.mpa.gov.sg","新加坡海事局。","ports",["港口代码"],"新加坡","英文",False),
("portofshanghai","上海港","https://www.portshanghai.com.cn","全球最大集装箱港。","ports",["港口代码"],"中国","中文",False),
("portof la","洛杉矶港","https://www.portoflosangeles.org","美国最大港。","ports",["港口代码"],"美国","英文",False),
("lloydslist","Lloyd's List","https://lloydslist.maritimeintelligence.informa.com","航运资讯。","ports",["航线资料"],"英国","英文",False),
("splash247","Splash 247","https://splash247.com","航运新闻。","ports",["航线资料"],"国际","英文",False),
("tradewinds","TradeWinds","https://www.tradewindsnews.com","航运新闻。","ports",["航线资料"],"挪威","英文",False),
("vesselfinder","VesselFinder","https://www.vesselfinder.com","船舶追踪。","ports",["港口代码"],"国际","英文",False),
("myshiptracking","MyShipTracking","https://www.myshiptracking.com","船舶实时追踪。","ports",["港口代码"],"国际","英文",False),
("fleetmon","FleetMon","https://www.fleetmon.com","船队监控。","ports",["港口代码"],"德国","英文",False),
# address 4->15 (+11)
("postalcode","Postal Code","https://worldpostalcode.com","世界邮编。","address",["邮编规则"],"国际","英文",False),
("zipcodes","Zip-Codes","https://www.zip-codes.com","美国邮编。","address",["邮编规则"],"美国","英文",False),
("postcode","Postcode","https://www.postcode.nl","荷兰邮编。","address",["邮编规则"],"荷兰","英文",False),
("addressformat","地址格式","https://www.address-formats.com","各国地址格式。","address",["地址格式"],"国际","英文",False),
("columbia_address","哥伦比亚地址格式","https://www.bitboost.com","地址验证工具。","address",["地址格式"],"美国","英文",False),
("countrydialing","国家区号","https://www.countrydialingcodes.com","电话区号。","address",["电话格式"],"国际","英文",False),
("howtocallabroad","How to Call Abroad","https://www.howtocallabroad.com","国际拨号指南。","address",["电话格式"],"美国","英文",False),
("royalmail_postcode","英国邮编","https://www.royalmail.com/find-a-postcode","英国邮编查询。","address",["邮编规则"],"英国","英文",False),
# countries 5->15 (+10)
("infoplease","Infoplease","https://www.infoplease.com","国家百科。","countries",["国家资料"],"美国","英文",False),
("britannica","大英百科","https://www.britannica.com","权威百科全书。","countries",["国家资料"],"英国","英文",False),
("worldatlas","WorldAtlas","https://www.worldatlas.com","世界地图集。","countries",["国家资料"],"加拿大","英文",False),
("theodora","Theodora","https://theodora.com","国家资料 CIA。","countries",["国家资料"],"美国","英文",False),
("everyculture","EveryCulture","https://www.everyculture.com","各国文化。","countries",["国家资料"],"美国","英文",False),
("countrymeters","Countrymeters","https://countrymeters.info","人口实时统计。","countries",["国家资料"],"国际","英文",False),
("gapminder","Gapminder","https://www.gapminder.org","全球发展数据。","countries",["国家资料"],"瑞典","英文",False),
("ourworldindata","Our World in Data","https://ourworldindata.org","全球数据可视化。","countries",["国家资料"],"英国","英文",False),
("un_data","UN Data","https://data.un.org","联合国数据。","countries",["国家资料"],"国际","英文",False),
("oecd_data","OECD Data","https://data.oecd.org","经合组织数据。","countries",["国家资料"],"法国","英文",False),
("mapcarta","Mapcarta","https://mapcarta.com","开放地图。","cities",["城市资料"],"国际","英文",False),
("wikimap","Wikimap","https://www.wikimap.org","维基城市地图。","cities",["城市资料"],"国际","英文",False),
("port_arrivals","Port Arrivals","https://www.portarrivals.com","港口到港查询。","ports",["港口代码"],"国际","英文",False),
("seavantage","SeaVantage","https://www.seavantage.com","船舶追踪。","ports",["港口代码"],"韩国","英文",False),
("zipcodebase","ZipcodeBase","https://zipcodebase.com","邮编 API。","address",["邮编规则"],"国际","英文",False),
]
