# 第 D 批：学习/学术/文档/新闻/翻译
BATCHD = [
("edx","edX","https://www.edx.org","哈佛MIT创办的在线课程平台。","learn",["在线课程"],"美国","英文",False),
("udemy","Udemy","https://www.udemy.com","技能课程市场。","learn",["在线课程"],"美国","英文",False),
("udacity","Udacity","https://www.udacity.com","硅谷在线技术课程。","learn",["在线课程"],"美国","英文",False),
("kaggle_learn","Kaggle Learn","https://www.kaggle.com/learn","免费数据科学微课程。","learn",["编程学习"],"美国","英文",False),
("codecademy","Codecademy","https://www.codecademy.com","交互式编程学习。","learn",["编程学习"],"美国","英文",False),
("leetcode","LeetCode","https://leetcode.com","程序员刷题平台。","learn",["编程学习"],"美国","英文",False),
("leetcode_cn","力扣","https://leetcode.cn","中文刷题平台。","learn",["编程学习"],"中国","中文",False),
("duolingo","多邻国","https://www.duolingo.com","游戏化语言学习。","learn",["英语学习"],"美国","英文",False),
("bbc_learning","BBC Learning English","https://www.bbc.co.uk/learningenglish","BBC 英语学习。","learn",["英语学习"],"英国","英文",False),
("ted","TED","https://www.ted.com","全球知名演讲平台。","learn",["在线课程"],"美国","英文",False),
("wiki_how","wikiHow","https://www.wikihow.com","生活技能指南。","learn",["学术资源"],"美国","英文",False),
("openstax","OpenStax","https://openstax.org","免费大学教材。","learn",["学术资源"],"美国","英文",False),
("mit_ocw","MIT OpenCourseWare","https://ocw.mit.edu","MIT 免费开放课程。","learn",["在线课程"],"美国","英文",False),
("zhihu","知乎","https://www.zhihu.com","中文问答社区。","learn",["学术资源"],"中国","中文",False),
("jianshu","简书","https://www.jianshu.com","中文创作社区。","learn",["学术资源"],"中国","中文",False),
("semanticscholar","Semantic Scholar","https://www.semanticscholar.org","AI 驱动的学术搜索。","academic",["学术搜索"],"美国","英文",False),
("researchgate","ResearchGate","https://www.researchgate.net","科研人员社交网络。","academic",["论文平台"],"德国","英文",False),
("scihub","Sci-Hub","https://www.sci-hub.st","开放获取论文（注意版权）。","academic",["论文平台"],"国际","英文",False),
("jstor","JSTOR","https://www.jstor.org","学术期刊档案库。","academic",["论文平台"],"美国","英文",False),
("nature","Nature","https://www.nature.com","顶级科学期刊。","academic",["科研机构"],"英国","英文",False),
("science","Science","https://www.science.org","顶级科学期刊。","academic",["科研机构"],"美国","英文",False),
("plos","PLOS","https://plos.org","开放获取科学出版。","academic",["论文平台"],"美国","英文",False),
("orcid","ORCID","https://orcid.org","学者身份标识。","academic",["科研机构"],"国际","英文",False),
("gitbook","GitBook","https://www.gitbook.com","文档协作平台。","docs",["技术文档"],"美国","英文",False),
("readthedocs","Read the Docs","https://readthedocs.org","开源文档托管。","docs",["技术文档","开源"],"美国","英文",False),
("devdocs","DevDocs","https://devdocs.io","开发者文档速查。","docs",["技术文档"],"国际","英文",False),
("overapi","OverAPI","https://overapi.com","速查表合集。","docs",["技术文档"],"国际","英文",False),
("reuters","路透社","https://www.reuters.com","国际权威通讯社。","news",["国际新闻"],"英国","英文",False),
("apnews","美联社","https://apnews.com","美国权威通讯社。","news",["国际新闻"],"美国","英文",False),
("guardian","卫报","https://www.theguardian.com","英国知名媒体。","news",["国际新闻"],"英国","英文",False),
("nyt","纽约时报","https://www.nytimes.com","美国主流大报。","news",["国际新闻"],"美国","英文",False),
("wsj","华尔街日报","https://www.wsj.com","财经权威媒体。","news",["财经新闻"],"美国","英文",False),
("ft","金融时报","https://www.ft.com","英国财经媒体。","news",["财经新闻"],"英国","英文",False),
("caixin","财新","https://www.caixin.com","中国财经媒体。","news",["财经新闻"],"中国","中文",False),
("thepaper","澎湃新闻","https://www.thepaper.cn","上海报业新媒体。","news",["国际新闻"],"中国","中文",False),
("hackernews","Hacker News","https://news.ycombinator.com","Y Combinator 技术社区。","news",["科技新闻"],"美国","英文",False),
("theverge","The Verge","https://www.theverge.com","科技文化媒体。","news",["科技新闻"],"美国","英文",False),
("wired","Wired","https://www.wired.com","科技杂志。","news",["科技新闻"],"美国","英文",False),
("baidu_translate","百度翻译","https://fanyi.baidu.com","百度在线翻译。","translate",["在线翻译"],"中国","中文",False),
("tencent_translate","腾讯翻译君","https://fanyi.qq.com","腾讯在线翻译。","translate",["在线翻译"],"中国","中文",False),
]
