# 第 M 批：地图/文档/求职（目标各 24）
BATCHM = [
# maps 7->24 (+17)
("bingmaps","Bing Maps","https://www.bing.com/maps","微软地图。","maps",["地图服务"],"美国","英文",False),
("applemaps","Apple Maps","https://maps.apple.com","苹果地图。","maps",["地图服务"],"美国","英文",False),
("yandexmaps","Yandex Maps","https://yandex.com/maps","Yandex 地图。","maps",["地图服务"],"俄罗斯","英文",False),
("navermaps","Naver Map","https://map.naver.com","韩国地图。","maps",["地图服务"],"韩国","韩文",False),
("kakaomap","KakaoMap","https://map.kakao.com","韩国地图。","maps",["地图服务"],"韩国","韩文",False),
("mapbox","Mapbox","https://www.mapbox.com","地图平台。","maps",["地图服务"],"美国","英文",False),
("leaflet","Leaflet","https://leafletjs.com","开源地图库。","maps",["地图服务","开源"],"国际","英文",False),
("openlayers","OpenLayers","https://openlayers.org","开源地图库。","maps",["地图服务","开源"],"国际","英文",False),
("carto","CARTO","https://carto.com","位置智能。","maps",["地图服务"],"美国","英文",False),
("mapillary","Mapillary","https://www.mapillary.com","街景众包。","maps",["卫星地图"],"瑞典","英文",False),
("strava","Strava","https://www.strava.com","运动轨迹。","maps",["地图服务"],"美国","英文",False),
("alltrails","AllTrails","https://www.alltrails.com","徒步路线。","maps",["地图服务"],"美国","英文",False),
("komoot","komoot","https://www.komoot.com","户外路线。","maps",["地图服务"],"德国","英文",False),
("waze","Waze","https://www.waze.com","众包导航。","maps",["地图服务"],"以色列","英文",False),
("sygic","Sygic","https://www.sygic.com","离线导航。","maps",["地图服务"],"斯洛伐克","英文",False),
("mapsme","MAPS.ME","https://maps.me","离线地图。","maps",["地图服务"],"国际","英文",False),
# docs 7->24 (+17)
("notion_docs","Notion 文档","https://www.notion.so","笔记（补）。","docs",["技术文档"],"美国","英文",False),
("confluence","Confluence","https://www.atlassian.com/software/confluence","团队文档。","docs",["技术文档"],"澳大利亚","英文",False),
("slab","Slab","https://slab.com","团队知识库。","docs",["技术文档"],"美国","英文",False),
("outline","Outline","https://www.getoutline.com","开源知识库。","docs",["技术文档","开源"],"国际","英文",False),
("bookstack","BookStack","https://www.bookstackapp.com","开源文档。","docs",["技术文档","开源"],"英国","英文",False),
("docusaurus","Docusaurus","https://docusaurus.io","文档网站生成。","docs",["技术文档","开源"],"美国","英文",False),
("vuepress","VuePress","https://vuepress.vuejs.org","文档生成器。","docs",["技术文档","开源"],"国际","英文",False),
("mkdocs","MkDocs","https://www.mkdocs.org","文档生成。","docs",["技术文档","开源"],"国际","英文",False),
("sphinx","Sphinx","https://www.sphinx-doc.org","文档工具。","docs",["技术文档","开源"],"国际","英文",False),
("mdbook","mdBook","https://rust-lang.github.io/mdBook","Rust 文档书。","docs",["技术文档","开源"],"国际","英文",False),
("readme","ReadMe","https://readme.com","API 文档。","docs",["API文档"],"美国","英文",False),
("stoplight","Stoplight","https://stoplight.io","API 设计。","docs",["API文档"],"美国","英文",False),
("postman_docs","Postman 文档","https://learning.postman.com","API 文档（补）。","docs",["API文档"],"美国","英文",False),
("swaggerhub","SwaggerHub","https://swagger.io/tools/swaggerhub","API 文档。","docs",["API文档"],"美国","英文",False),
("redoc","Redoc","https://redocly.com","API 文档渲染。","docs",["API文档"],"国际","英文",False),
("devhints","Devhints","https://devhints.io","速查表。","docs",["技术文档"],"国际","英文",False),
# jobs 7->24 (+17)
("linkedin_jobs","LinkedIn Jobs","https://www.linkedin.com/jobs","职业社交招聘。","jobs",["招聘网站"],"美国","英文",False),
("angelist","Wellfound","https://wellfound.com","初创招聘。","jobs",["招聘网站"],"美国","英文",False),
("stackoverflow_jobs","Stack Overflow Jobs","https://stackoverflow.com/jobs","程序员招聘。","jobs",["招聘网站"],"美国","英文",False),
("github_jobs","GitHub Jobs","https://www.github.careers","GitHub 招聘。","jobs",["招聘网站"],"美国","英文",False),
("dice","Dice","https://www.dice.com","技术招聘。","jobs",["招聘网站"],"美国","英文",False),
("monster","Monster","https://www.monster.com","招聘网站。","jobs",["招聘网站"],"美国","英文",False),
("careerbuilder","CareerBuilder","https://www.careerbuilder.com","招聘。","jobs",["招聘网站"],"美国","英文",False),
("simplyhired","SimplyHired","https://www.simplyhired.com","招聘搜索。","jobs",["招聘网站"],"美国","英文",False),
("ziprecruiter","ZipRecruiter","https://www.ziprecruiter.com","招聘。","jobs",["招聘网站"],"美国","英文",False),
("flexjobs","FlexJobs","https://www.flexjobs.com","远程工作。","jobs",["远程工作"],"美国","英文",False),
("remoteok","Remote OK","https://remoteok.com","远程招聘。","jobs",["远程工作"],"国际","英文",False),
("weworkremotely","We Work Remotely","https://weworkremotely.com","远程工作。","jobs",["远程工作"],"美国","英文",False),
("upwork","Upwork","https://www.upwork.com","自由职业。","jobs",["自由职业"],"美国","英文",False),
("fiverr","Fiverr","https://www.fiverr.com","自由职业。","jobs",["自由职业"],"以色列","英文",False),
("toptal","Toptal","https://www.toptal.com","高端自由职业。","jobs",["自由职业"],"美国","英文",False),
("freelancer","Freelancer","https://www.freelancer.com","自由职业。","jobs",["自由职业"],"澳大利亚","英文",False),
("guru","Guru","https://www.guru.com","自由职业。","jobs",["自由职业"],"美国","英文",False),
("peopleperhour","PeoplePerHour","https://www.peopleperhour.com","自由职业。","jobs",["自由职业"],"英国","英文",False),
]
