# 第 P 批：办公/搜索/视频/云盘（目标各 24）
BATCHP = [
# office 11->24 (+13)
("dingtalk","钉钉","https://www.dingtalk.com","阿里协作。","office",["Office"],"中国","中文",False),
("wecom","企业微信","https://work.weixin.qq.com","腾讯协作。","office",["Office"],"中国","中文",False),
("lark","Lark","https://www.larksuite.com","飞书海外版。","office",["Office"],"新加坡","英文",False),
("asana","Asana","https://asana.com","项目管理。","office",["Office"],"美国","英文",False),
("trello","Trello","https://trello.com","看板管理。","office",["Office"],"美国","英文",False),
("monday","Monday.com","https://monday.com","项目管理。","office",["Office"],"以色列","英文",False),
("clickup","ClickUp","https://clickup.com","项目管理。","office",["Office"],"美国","英文",False),
("evernote","Evernote","https://evernote.com","笔记软件。","office",["Office"],"美国","英文",False),
("onenote","OneNote","https://www.onenote.com","微软笔记。","office",["Office"],"美国","英文",False),
("joplin","Joplin","https://joplinapp.org","开源笔记。","office",["Office","开源"],"国际","英文",False),
("obsidian","Obsidian","https://obsidian.md","知识管理。","office",["Office"],"美国","英文",False),
# search 12->24 (+12)
("mojeek","Mojeek","https://www.mojeek.com","独立搜索引擎。","search",["综合搜索"],"英国","英文",False),
("swisscows","Swisscows","https://swisscows.com","隐私搜索。","search",["综合搜索"],"瑞士","英文",False),
("qwant","Qwant","https://www.qwant.com","欧洲搜索引擎。","search",["综合搜索"],"法国","英文",False),
("metager","MetaGer","https://metager.org","元搜索。","search",["综合搜索"],"德国","英文",False),
("searx","SearXNG","https://docs.searxng.org","开源元搜索。","search",["综合搜索","开源"],"国际","英文",False),
("kagi","Kagi","https://kagi.com","付费无广告搜索。","search",["综合搜索"],"美国","英文",False),
# video 12->24 (+12)
("tiktok","TikTok","https://www.tiktok.com","短视频。","video",["短视频"],"国际","英文",False),
("shorts","YouTube Shorts","https://www.youtube.com/shorts","短视频。","video",["短视频"],"美国","英文",False),
("rumble","Rumble","https://rumble.com","视频平台。","video",["长视频"],"加拿大","英文",False),
("odysee","Odysee","https://odysee.com","去中心化视频。","video",["长视频"],"美国","英文",False),
("peertube","PeerTube","https://joinpeertube.org","开源视频。","video",["长视频","开源"],"法国","英文",False),
("acfun","AcFun","https://www.acfun.cn","弹幕视频。","video",["长视频"],"中国","中文",False),
("sohu_video","搜狐视频","https://tv.sohu.com","长视频。","video",["长视频"],"中国","中文",False),
# cloud 12->24 (+12)
("pcloud","pCloud","https://www.pcloud.com","云存储。","cloud",["云存储"],"瑞士","英文",False),
("icedrive","Icedrive","https://icedrive.net","云存储。","cloud",["云存储"],"英国","英文",False),
("sync","Sync.com","https://www.sync.com","加密云存储。","cloud",["云存储"],"加拿大","英文",False),
("tresorit","Tresorit","https://tresorit.com","加密云存储。","cloud",["云存储"],"瑞士","英文",False),
("filen","Filen","https://filen.io","加密云存储。","cloud",["云存储"],"德国","英文",False),
("koofr","Koofr","https://koofr.eu","云存储。","cloud",["云存储"],"斯洛文尼亚","英文",False),
("box","Box","https://www.box.com","企业云存储。","cloud",["云存储"],"美国","英文",False),
("nextcloud","Nextcloud","https://nextcloud.com","自建云盘。","cloud",["云存储","开源"],"德国","英文",False),
("seafile","Seafile","https://www.seafile.com","自建云盘。","cloud",["云存储","开源"],"中国","英文",False),
("yandex_disk","Yandex Disk","https://disk.yandex.com","Yandex 云盘。","cloud",["云存储"],"俄罗斯","英文",False),
("mailru_cloud","VK 云盘","https://cloud.mail.ru","俄罗斯云盘。","cloud",["云存储"],"俄罗斯","俄文",False),
("mediafire","MediaFire","https://www.mediafire.com","文件分享。","cloud",["文件分享"],"美国","英文",False),
("4shared","4shared","https://www.4shared.com","文件分享。","cloud",["文件分享"],"乌克兰","英文",False),
("vimeo_staff","Vimeo Staff Picks","https://vimeo.com/channels/staffpicks","精选视频。","video",["长视频"],"美国","英文",False),
("ted_talks","TED Talks","https://www.ted.com/talks","演讲视频。","video",["教育视频"],"美国","英文",False),
("masterclass","MasterClass","https://www.masterclass.com","大师课程。","video",["教育视频"],"美国","英文",False),
("skillshare","Skillshare","https://www.skillshare.com","技能课程。","video",["教育视频"],"美国","英文",False),
]
