# 第 A 批：AI 专区扩充
BATCHA = [
("grok","Grok","https://grok.com","xAI 推出的 AI 助手，实时联网幽默风趣。","ai",["AI聊天","大模型"],"美国","英文",False),
("mistral","Mistral Le Chat","https://chat.mistral.ai","法国 Mistral AI 的对话助手，欧洲大模型代表。","ai",["AI聊天","大模型"],"法国","英文",False),
("llama","Meta AI","https://www.meta.ai","Meta 推出的 AI 助手，基于 Llama 开源模型。","ai",["AI聊天","大模型"],"美国","英文",False),
("poe","Poe","https://poe.com","Quora 出品，一个入口用遍多种 AI 模型。","ai",["AI聊天","大模型"],"美国","英文",False),
("characterai","Character.AI","https://character.ai","和虚拟角色聊天的 AI 平台。","ai",["AI聊天"],"美国","英文",False),
("you","You.com","https://you.com","AI 搜索引擎，问答带引用来源。","ai",["AI搜索"],"美国","英文",False),
("phind","Phind","https://www.phind.com","面向开发者的 AI 搜索引擎。","ai",["AI搜索","AI编程"],"美国","英文",False),
("blackbox","Blackbox AI","https://www.blackbox.ai","AI 编程助手，代码补全与问答。","ai",["AI编程"],"美国","英文",False),
("codeium","Codeium","https://codeium.com","免费的 AI 代码补全工具。","ai",["AI编程"],"美国","英文",False),
("tabnine","Tabnine","https://www.tabnine.com","AI 代码补全老牌工具。","ai",["AI编程"],"美国","英文",False),
("replit","Replit","https://replit.com","在线 AI 编程协作平台。","ai",["AI编程"],"美国","英文",False),
("v0","v0 by Vercel","https://v0.dev","一句话生成 React 界面的 AI 工具。","ai",["AI编程"],"美国","英文",False),
("bolt","Bolt.new","https://bolt.new","浏览器里的 AI 全栈应用生成器。","ai",["AI编程"],"美国","英文",False),
("lovable","Lovable","https://lovable.dev","用自然语言创建完整 Web 应用。","ai",["AI编程"],"瑞典","英文",False),
("udio","Udio","https://www.udio.com","AI 音乐生成，媲美 Suno。","ai",["AI音乐"],"美国","英文",False),
("elevenlabs","ElevenLabs","https://elevenlabs.io","顶级 AI 语音合成与克隆。","ai",["AI配音"],"美国","英文",False),
("heygen","HeyGen","https://www.heygen.com","AI 数字人视频生成平台。","ai",["AI视频","AI配音"],"美国","英文",False),
("pika","Pika","https://pika.art","AI 视频生成工具。","ai",["AI视频"],"美国","英文",False),
("luma","Luma Dream Machine","https://lumalabs.ai","Luma 的 AI 视频生成模型。","ai",["AI视频"],"美国","英文",False),
("stability","Stability AI","https://stability.ai","Stable Diffusion 背后的公司。","ai",["AI绘图"],"英国","英文",False),
("leonardo","Leonardo AI","https://leonardo.ai","AI 绘画与游戏素材生成。","ai",["AI绘图"],"澳大利亚","英文",False),
("ideogram","Ideogram","https://ideogram.ai","擅长文字渲染的 AI 绘图。","ai",["AI绘图"],"美国","英文",False),
("civitai","Civitai","https://civitai.com","Stable Diffusion 模型分享社区。","ai",["AI绘图","AI模型"],"美国","英文",False),
("gamma","Gamma","https://gamma.app","AI 一键生成演示文稿。","ai",["AI办公"],"美国","英文",False),
("groq","Groq","https://groq.com","超高速 AI 推理芯片与云服务。","ai",["大模型","AI基础设施"],"美国","英文",False),
("together","Together AI","https://www.together.ai","开源模型推理云平台。","ai",["大模型","AI基础设施"],"美国","英文",False),
("replicate","Replicate","https://replicate.com","一键运行开源 AI 模型。","ai",["AI模型"],"美国","英文",False),
("langchain","LangChain","https://www.langchain.com","大模型应用开发框架。","ai",["AI Agent","开发框架"],"美国","英文",False),
("dify","Dify","https://dify.ai","开源的 LLM 应用开发平台。","ai",["AI Agent","开源"],"中国","中文",False),
("coze","Coze 扣子","https://www.coze.cn","字节跳动 AI Agent 搭建平台。","ai",["AI Agent"],"中国","中文",False),
]
