# 第 S 批：学习/设计/AI（目标 learn 35/design 35/ai 70）
BATCHS = [
# learn 19->35 (+16)
("pluralsight","Pluralsight","https://www.pluralsight.com","技术课程。","learn",["在线课程"],"美国","英文",False),
("lynda","LinkedIn Learning","https://www.linkedin.com/learning","职业课程。","learn",["在线课程"],"美国","英文",False),
("datacamp","DataCamp","https://www.datacamp.com","数据科学课程。","learn",["编程学习"],"美国","英文",False),
("educative","Educative","https://www.educative.io","交互式课程。","learn",["编程学习"],"美国","英文",False),
("exercism","Exercism","https://exercism.org","编程练习。","learn",["编程学习"],"国际","英文",False),
("the_odin_project","The Odin Project","https://www.theodinproject.com","全栈课程。","learn",["编程学习"],"国际","英文",False),
("cs50","CS50","https://cs50.harvard.edu","哈佛 CS 课。","learn",["编程学习"],"美国","英文",False),
("stanford_online","Stanford Online","https://online.stanford.edu","斯坦福在线。","learn",["在线课程"],"美国","英文",False),
("oyc_yale","Open Yale","https://oyc.yale.edu","耶鲁公开课。","learn",["在线课程"],"美国","英文",False),
("nptel","NPTEL","https://nptel.ac.in","印度在线课程。","learn",["在线课程"],"印度","英文",False),
# design 19->35 (+16)
("sketch","Sketch","https://www.sketch.com","Mac 设计工具。","design",["UI设计"],"荷兰","英文",False),
("framer","Framer","https://www.framer.com","网站设计。","design",["UI设计"],"荷兰","英文",False),
("webflow","Webflow","https://webflow.com","可视化建站。","design",["UI设计"],"美国","英文",False),
("invision","InVision","https://www.invisionapp.com","原型设计。","design",["UI设计"],"美国","英文",False),
("marvel","Marvel","https://marvelapp.com","原型设计。","design",["UI设计"],"英国","英文",False),
("principle","Principle","https://principleformac.com","动效设计。","design",["UI设计"],"美国","英文",False),
("protoio","Proto.io","https://proto.io","原型设计。","design",["UI设计"],"美国","英文",False),
("zeplin","Zeplin","https://zeplin.io","设计交付。","design",["UI设计"],"美国","英文",False),
("avocode","Avocode","https://avocode.com","设计交付。","design",["UI设计"],"捷克","英文",False),
("lottie","LottieFiles","https://lottiefiles.com","动效资源。","design",["UI设计"],"美国","英文",False),
("unDraw","unDraw","https://undraw.co","插画素材。","design",["图片素材"],"国际","英文",False),
("humaaans","Humaaans","https://www.humaaans.com","人物插画。","design",["图片素材"],"国际","英文",False),
("blush","Blush","https://blush.design","插画素材。","design",["图片素材"],"国际","英文",False),
# ai 50->70 (+20)
("anthropic","Anthropic","https://www.anthropic.com","Claude 公司。","ai",["大模型"],"美国","英文",False),
("openai","OpenAI","https://openai.com","ChatGPT 公司。","ai",["大模型"],"美国","英文",False),
("deepmind","Google DeepMind","https://deepmind.google","DeepMind。","ai",["大模型"],"英国","英文",False),
("meta_ai_research","Meta AI","https://ai.meta.com","Meta AI 研究。","ai",["大模型"],"美国","英文",False),
("cohere","Cohere","https://cohere.com","企业大模型。","ai",["大模型"],"加拿大","英文",False),
("ai21","AI21 Labs","https://www.ai21.com","大模型。","ai",["大模型"],"以色列","英文",False),
("inflection","Inflection","https://inflection.ai","Pi 助手公司。","ai",["大模型"],"美国","英文",False),
("adept","Adept","https://www.adept.ai","AI Agent。","ai",["AI Agent"],"美国","英文",False),
("datacamp2","DataCamp 官网","https://www.datacamp.com","数据课程（补）。","learn",["编程学习"],"美国","英文",False),
("brilliant","Brilliant","https://brilliant.org","STEM 学习。","learn",["在线课程"],"美国","英文",False),
("khan_for_kids","Khan Kids","https://www.khankids.org","儿童学习。","learn",["在线课程"],"美国","英文",False),
("scratch","Scratch","https://scratch.mit.edu","少儿编程。","learn",["编程学习"],"美国","英文",False),
("code_org","Code.org","https://code.org","编程教育。","learn",["编程学习"],"美国","英文",False),
("w3schools","W3Schools","https://www.w3schools.com","Web 教程。","learn",["编程学习"],"挪威","英文",False),
("tutorialspoint","TutorialsPoint","https://www.tutorialspoint.com","技术教程。","learn",["编程学习"],"印度","英文",False),
("geeksforgeeks","GeeksforGeeks","https://www.geeksforgeeks.org","编程教程。","learn",["编程学习"],"印度","英文",False),
("javatpoint","JavaTpoint","https://www.javatpoint.com","技术教程。","learn",["编程学习"],"印度","英文",False),
("programiz","Programiz","https://www.programiz.com","编程教程。","learn",["编程学习"],"尼泊尔","英文",False),
("artstation","ArtStation","https://www.artstation.com","艺术家社区。","design",["UI设计"],"加拿大","英文",False),
("cargo","Cargo","https://cargo.site","作品集网站。","design",["UI设计"],"美国","英文",False),
("readymag","Readymag","https://readymag.com","在线出版设计。","design",["UI设计"],"美国","英文",False),
("spline","Spline","https://spline.design","3D 设计。","design",["3D模型"],"美国","英文",False),
("vectary","Vectary","https://www.vectary.com","3D 设计。","design",["3D模型"],"斯洛伐克","英文",False),
("tinkercad","Tinkercad","https://www.tinkercad.com","3D 建模入门。","design",["3D模型"],"美国","英文",False),
("midjourney_docs","Midjourney 文档","https://docs.midjourney.com","MJ 文档。","ai",["AI绘图"],"美国","英文",False),
("stability_docs","Stability 文档","https://stability.ai/docs","文档。","ai",["AI绘图"],"英国","英文",False),
("openai_docs","OpenAI 文档","https://platform.openai.com/docs","API 文档。","ai",["大模型"],"美国","英文",False),
("anthropic_docs","Anthropic 文档","https://docs.anthropic.com","API 文档。","ai",["大模型"],"美国","英文",False),
("google_ai_docs","Google AI 文档","https://ai.google.dev","AI 文档。","ai",["大模型"],"美国","英文",False),
("mistral_docs","Mistral 文档","https://docs.mistral.ai","文档。","ai",["大模型"],"法国","英文",False),
("groq_docs","Groq 文档","https://console.groq.com/docs","文档。","ai",["大模型"],"美国","英文",False),
("together_docs","Together 文档","https://docs.together.ai","文档。","ai",["大模型"],"美国","英文",False),
("replicate_docs","Replicate 文档","https://replicate.com/docs","文档。","ai",["AI模型"],"美国","英文",False),
]
