# 第 E 批：游戏/音乐/视频/社交
BATCHE = [
("gog","GOG","https://www.gog.com","无 DRM 游戏商店。","games",["游戏平台"],"波兰","英文",False),
("itchio","itch.io","https://itch.io","独立游戏平台。","games",["游戏平台"],"美国","英文",False),
("roblox","Roblox","https://www.roblox.com","用户创作游戏平台。","games",["游戏平台"],"美国","英文",False),
("minecraft","Minecraft","https://www.minecraft.net","沙盒游戏官网。","games",["游戏平台"],"瑞典","英文",False),
("ign","IGN","https://www.ign.com","游戏媒体。","games",["游戏媒体"],"美国","英文",False),
("gamespot","GameSpot","https://www.gamespot.com","游戏新闻评测。","games",["游戏媒体"],"美国","英文",False),
("pcgamer","PC Gamer","https://www.pcgamer.com","PC 游戏媒体。","games",["游戏媒体"],"英国","英文",False),
("twitch","Twitch","https://www.twitch.tv","游戏直播平台。","games",["直播平台"],"美国","英文",False),
("discord","Discord","https://discord.com","游戏玩家社区通讯。","social",["即时通讯"],"美国","英文",False),
("huya","虎牙直播","https://www.huya.com","游戏直播平台。","video",["直播平台"],"中国","中文",False),
("douyu","斗鱼","https://www.douyu.com","游戏直播平台。","video",["直播平台"],"中国","中文",False),
("iqiyi","爱奇艺","https://www.iqiyi.com","长视频平台。","video",["长视频"],"中国","中文",False),
("tencent_video","腾讯视频","https://v.qq.com","长视频平台。","video",["长视频"],"中国","中文",False),
("youku","优酷","https://www.youku.com","长视频平台。","video",["长视频"],"中国","中文",False),
("vimeo","Vimeo","https://vimeo.com","高清视频分享。","video",["长视频"],"美国","英文",False),
("dailymotion","Dailymotion","https://www.dailymotion.com","视频分享平台。","video",["长视频"],"法国","英文",False),
("kuaishou","快手","https://www.kuaishou.com","短视频平台。","video",["短视频"],"中国","中文",False),
("xiaohongshu","小红书","https://www.xiaohongshu.com","生活方式社区。","social",["社交平台"],"中国","中文",False),
("douban","豆瓣","https://www.douban.com","文艺青年社区。","social",["社区论坛"],"中国","中文",False),
("tieba","百度贴吧","https://tieba.baidu.com","中文兴趣社区。","social",["社区论坛"],"中国","中文",False),
("instagram","Instagram","https://www.instagram.com","图片社交平台。","social",["社交平台"],"美国","英文",False),
("facebook","Facebook","https://www.facebook.com","全球最大社交网络。","social",["社交平台"],"美国","英文",False),
("linkedin_cn","LinkedIn 中国","https://www.linkedin.cn","职业社交（中国版）。","social",["社交平台"],"中国","中文",False),
("whatsapp","WhatsApp","https://www.whatsapp.com","全球即时通讯。","social",["即时通讯"],"美国","英文",False),
("slack","Slack","https://slack.com","团队协作通讯。","social",["企业协作"],"美国","英文",False),
("zoom","Zoom","https://zoom.us","视频会议。","social",["视频会议"],"美国","英文",False),
("teams","Microsoft Teams","https://www.microsoft.com/microsoft-teams","微软协作平台。","social",["企业协作"],"美国","英文",False),
("apple_music","Apple Music","https://music.apple.com","苹果音乐流媒体。","music",["音乐平台"],"美国","英文",False),
("youtube_music","YouTube Music","https://music.youtube.com","YouTube 音乐服务。","music",["音乐平台"],"美国","英文",False),
("qq_music","QQ音乐","https://y.qq.com","腾讯音乐平台。","music",["音乐平台"],"中国","中文",False),
("kugou","酷狗音乐","https://www.kugou.com","音乐播放器。","music",["音乐平台"],"中国","中文",False),
("kuwo","酷我音乐","https://www.kuwo.cn","音乐平台。","music",["音乐平台"],"中国","中文",False),
("bandcamp","Bandcamp","https://bandcamp.com","独立音乐人平台。","music",["音乐平台"],"美国","英文",False),
("soundcloud","SoundCloud","https://soundcloud.com","音乐分享社区。","music",["音乐平台"],"德国","英文",False),
("lastfm","Last.fm","https://www.last.fm","音乐推荐社区。","music",["音乐平台"],"英国","英文",False),
("ximalaya","喜马拉雅","https://www.ximalaya.com","音频播客平台。","music",["播客"],"中国","中文",False),
("lizhi","荔枝","https://www.lizhi.fm","播客平台。","music",["播客"],"中国","中文",False),
("douban_music","豆瓣音乐","https://music.douban.com","音乐发现社区。","music",["音乐平台"],"中国","中文",False),
("genius","Genius","https://genius.com","歌词解析社区。","music",["音乐平台"],"美国","英文",False),
("ultimate_guitar","Ultimate Guitar","https://www.ultimate-guitar.com","吉他谱社区。","music",["音乐平台"],"美国","英文",False),
]
