# 第 H 批：搜索/地图/邮箱/云盘/下载/浏览器/安卓
BATCHH = [
("ecosia","Ecosia","https://www.ecosia.org","种树搜索引擎。","search",["综合搜索"],"德国","英文",False),
("brave_search","Brave Search","https://search.brave.com","隐私搜索引擎。","search",["综合搜索","隐私"],"美国","英文",False),
("yandex","Yandex","https://yandex.com","俄罗斯搜索引擎。","search",["综合搜索"],"俄罗斯","英文",False),
("naver","Naver","https://www.naver.com","韩国最大搜索引擎。","search",["综合搜索"],"韩国","韩文",False),
("sogou","搜狗搜索","https://www.sogou.com","中文搜索引擎。","search",["综合搜索"],"中国","中文",False),
("360search","360搜索","https://www.so.com","奇虎搜索引擎。","search",["综合搜索"],"中国","中文",False),
("bing_images","Bing 图片","https://www.bing.com/images","Bing 图片搜索。","search",["图片搜索"],"美国","英文",False),
("unsplash_search","Unsplash 搜索","https://unsplash.com","免费图片搜索。","search",["图片搜索"],"加拿大","英文",False),
("baidu_map","百度地图","https://map.baidu.com","百度地图服务。","maps",["地图服务"],"中国","中文",False),
("tencent_map","腾讯地图","https://map.qq.com","腾讯地图服务。","maps",["地图服务"],"中国","中文",False),
("here","HERE WeGo","https://www.here.com","HERE 地图。","maps",["地图服务"],"荷兰","英文",False),
("wikimapia","Wikimapia","https://wikimapia.org","维基地图。","maps",["地图服务"],"国际","英文",False),
("protonmail","Proton Mail","https://proton.me/mail","加密邮箱。","email",["免费邮箱","隐私"],"瑞士","英文",False),
("tutanota","Tuta","https://tuta.com","加密邮箱。","email",["免费邮箱","隐私"],"德国","英文",False),
("163mail","163邮箱","https://mail.163.com","网易邮箱。","email",["免费邮箱"],"中国","中文",False),
("126mail","126邮箱","https://mail.126.com","网易邮箱。","email",["免费邮箱"],"中国","中文",False),
("sina_mail","新浪邮箱","https://mail.sina.com.cn","新浪邮箱。","email",["免费邮箱"],"中国","中文",False),
("onedrive","OneDrive","https://onedrive.live.com","微软云存储。","cloud",["云存储"],"美国","英文",False),
("icloud","iCloud","https://www.icloud.com","苹果云服务。","cloud",["云存储"],"美国","英文",False),
("mega","MEGA","https://mega.io","加密云存储。","cloud",["云存储"],"新西兰","英文",False),
("alipan","阿里云盘","https://www.alipan.com","阿里个人云盘。","cloud",["网盘"],"中国","中文",False),
("quark_pan","夸克网盘","https://pan.quark.cn","夸克网盘。","cloud",["网盘"],"中国","中文",False),
("lanzou","蓝奏云","https://www.lanzou.com","简洁网盘。","cloud",["网盘"],"中国","中文",False),
("ctfile","城通网盘","https://www.ctfile.com","网盘服务。","cloud",["网盘"],"中国","中文",False),
("weiyun","微云","https://www.weiyun.com","腾讯云盘。","cloud",["网盘"],"中国","中文",False),
("jianzuo","坚果云","https://www.jianguoyun.com","同步网盘。","cloud",["云存储"],"中国","中文",False),
("chrome_webstore","Chrome 应用店","https://chromewebstore.google.com","Chrome 扩展商店。","download",["软件"],"美国","英文",False),
("softonic","Softonic","https://www.softonic.com","软件下载站。","download",["软件"],"西班牙","英文",False),
("filehorse","FileHorse","https://www.filehorse.com","软件下载。","download",["软件"],"美国","英文",False),
("majorgeeks","MajorGeeks","https://www.majorgeeks.com","软件下载。","download",["软件"],"美国","英文",False),
("fosshub","FossHub","https://www.fosshub.com","开源软件下载。","download",["软件","开源"],"罗马尼亚","英文",False),
("ninite","Ninite","https://ninite.com","批量装机工具。","download",["软件"],"美国","英文",False),
("rufus","Rufus","https://rufus.ie","启动盘制作。","download",["系统镜像"],"国际","英文",False),
("ventoy","Ventoy","https://www.ventoy.net","多启动U盘工具。","download",["系统镜像"],"中国","英文",False),
("archlinux","Arch Linux","https://archlinux.org","滚动发行版。","download",["系统镜像"],"国际","英文",False),
("fedora","Fedora","https://fedoraproject.org","红帽社区版。","download",["系统镜像"],"美国","英文",False),
("manjaro","Manjaro","https://manjaro.org","易用 Arch 衍生版。","download",["系统镜像"],"德国","英文",False),
("deepin","深度 deepin","https://www.deepin.org","国产 Linux 发行版。","download",["系统镜像"],"中国","中文",False),
("kali","Kali Linux","https://www.kali.org","安全测试发行版。","download",["系统镜像"],"美国","英文",False),
("brave","Brave","https://brave.com","隐私浏览器。","browser",["隐私浏览器"],"美国","英文",False),
("vivaldi","Vivaldi","https://vivaldi.com","高度定制浏览器。","browser",["Chromium"],"挪威","英文",False),
("arc","Arc","https://arc.net","新锐浏览器。","browser",["Chromium"],"美国","英文",False),
("tor","Tor Browser","https://www.torproject.org","匿名浏览器。","browser",["隐私浏览器"],"国际","英文",False),
("opera","Opera","https://www.opera.com","老牌浏览器。","browser",["Chromium"],"挪威","英文",False),
("samsung_internet","三星浏览器","https://www.samsung.com/us/apps/samsung-internet","三星浏览器。","browser",["Chromium"],"韩国","英文",False),
("via","Via 浏览器","https://viayoo.com","轻量安卓浏览器。","browser",["Chromium"],"中国","中文",False),
("coolapk","酷安","https://www.coolapk.com","安卓应用社区。","android",["APK"],"中国","中文",False),
("apkpure","APKPure","https://apkpure.com","APK 下载站。","android",["APK"],"国际","英文",False),
("uptodown","Uptodown","https://www.uptodown.com","应用下载站。","android",["APK"],"西班牙","英文",False),
("xda","XDA Developers","https://www.xda-developers.com","安卓开发者社区。","android",["安卓开发"],"美国","英文",False),
("android_dev","Android Developers","https://developer.android.com","安卓官方开发文档。","android",["安卓开发"],"美国","英文",False),
("lineageos","LineageOS","https://lineageos.org","开源安卓 ROM。","android",["ROM","开源"],"国际","英文",False),
("twrp","TWRP","https://twrp.me","第三方 Recovery。","android",["ROM"],"美国","英文",False),
("scrcpy","scrcpy","https://github.com/Genymobile/scrcpy","安卓投屏工具。","android",["安卓开发","开源"],"法国","英文",False),
("adb","ADB 文档","https://developer.android.com/tools/adb","安卓调试桥。","android",["安卓开发"],"美国","英文",False),
("aurora","Aurora Store","https://auroraoss.com","开源 Play 商店客户端。","android",["APK","开源"],"国际","英文",False),
("gsmarena","GSMArena","https://www.gsmarena.com","手机参数库。","android",["APK"],"英国","英文",False),
]
