# 第 R 批：社交/新闻/工具/运维/下载/音乐（目标各 24）
BATCHR = [
# social 15->24 (+9)
("mastodon","Mastodon","https://mastodon.social","去中心化社交。","social",["社交平台","开源"],"国际","英文",False),
("bluesky","Bluesky","https://bsky.app","去中心化社交。","social",["社交平台"],"美国","英文",False),
("threads","Threads","https://www.threads.net","Meta 社交。","social",["社交平台"],"美国","英文",False),
("signal","Signal","https://signal.org","加密通讯。","social",["即时通讯"],"美国","英文",False),
("line","LINE","https://line.me","日韩通讯。","social",["即时通讯"],"日本","多语言",False),
# news 15->24 (+9)
("aljazeera","半岛电视台","https://www.aljazeera.com","国际新闻。","news",["国际新闻"],"卡塔尔","英文",False),
("dw","德国之声","https://www.dw.com","德国国际媒体。","news",["国际新闻"],"德国","多语言",False),
("france24","France 24","https://www.france24.com","法国国际新闻。","news",["国际新闻"],"法国","多语言",False),
("nhk_world","NHK World","https://www3.nhk.or.jp/nhkworld","日本国际放送。","news",["国际新闻"],"日本","英文",False),
("cna","CNA","https://www.channelnewsasia.com","新加坡新闻。","news",["国际新闻"],"新加坡","英文",False),
# utils 15->24 (+9)
("codebeautify","CodeBeautify","https://codebeautify.org","代码格式化。","utils",["开发工具"],"国际","英文",False),
("base64encode","Base64 Encode","https://www.base64encode.org","Base64 工具。","utils",["开发工具"],"国际","英文",False),
("urlencoder","URL Encoder","https://www.urlencoder.org","URL 编码。","utils",["开发工具"],"国际","英文",False),
("diffchecker","Diffchecker","https://www.diffchecker.com","文本对比。","utils",["开发工具"],"国际","英文",False),
("loremipsum","Lorem Ipsum","https://www.lipsum.com","占位文本。","utils",["开发工具"],"国际","英文",False),
("placeholder","Placeholder","https://placeholder.com","占位图。","utils",["开发工具"],"国际","英文",False),
("favicon_io","Favicon.io","https://favicon.io","图标生成。","utils",["开发工具"],"国际","英文",False),
# ops 16->24 (+8)
("rancher","Rancher","https://www.rancher.com","K8s 管理。","ops",["Kubernetes"],"美国","英文",False),
("k3s","K3s","https://k3s.io","轻量 K8s。","ops",["Kubernetes"],"美国","英文",False),
("helm","Helm","https://helm.sh","K8s 包管理。","ops",["Kubernetes"],"国际","英文",False),
("argocd","Argo CD","https://argo-cd.readthedocs.io","GitOps。","ops",["DevOps"],"国际","英文",False),
("fluxcd","FluxCD","https://fluxcd.io","GitOps。","ops",["DevOps"],"国际","英文",False),
# download 16->24 (+8)
("chocolatey","Chocolatey","https://chocolatey.org","Windows 包管理。","download",["软件"],"美国","英文",False),
("scoop","Scoop","https://scoop.sh","Windows 包管理。","download",["软件"],"国际","英文",False),
("winget","WinGet","https://learn.microsoft.com/windows/package-manager","微软包管理。","download",["软件"],"美国","英文",False),
("homebrew","Homebrew","https://brew.sh","macOS 包管理。","download",["软件"],"国际","英文",False),
# music 16->24 (+8)
("shazam","Shazam","https://www.shazam.com","听歌识曲。","music",["音乐平台"],"美国","英文",False),
("musixmatch","Musixmatch","https://www.musixmatch.com","歌词。","music",["音乐平台"],"意大利","英文",False),
("tunefind","Tunefind","https://www.tunefind.com","影视音乐。","music",["音乐平台"],"美国","英文",False),
("every_noise","Every Noise","https://everynoise.com","音乐流派图谱。","music",["音乐平台"],"国际","英文",False),
("radio_garden","Radio Garden","https://radio.garden","全球电台。","music",["网络电台"],"国际","英文",False),
("my_tuner","myTuner","https://www.mytuner-radio.com","网络电台。","music",["网络电台"],"葡萄牙","英文",False),
("vkontakte","VK","https://vk.com","俄罗斯社交。","social",["社交平台"],"俄罗斯","俄文",False),
("ok_ru","OK.ru","https://ok.ru","俄罗斯社交。","social",["社交平台"],"俄罗斯","俄文",False),
("wechat","微信","https://weixin.qq.com","腾讯通讯。","social",["即时通讯"],"中国","中文",False),
("qq","QQ","https://im.qq.com","腾讯通讯。","social",["即时通讯"],"中国","中文",False),
("npr_news","NPR","https://www.npr.org","美国公共广播。","news",["国际新闻"],"美国","英文",False),
("pbs","PBS","https://www.pbs.org","美国公共电视。","news",["国际新闻"],"美国","英文",False),
("euronews","Euronews","https://www.euronews.com","欧洲新闻。","news",["国际新闻"],"法国","多语言",False),
("rt_news","RT","https://www.rt.com","俄罗斯国际新闻。","news",["国际新闻"],"俄罗斯","英文",False),
("globaltimes","环球时报","https://www.globaltimes.cn","中国英文媒体。","news",["国际新闻"],"中国","英文",False),
("chinadaily","中国日报","https://www.chinadaily.com.cn","中国英文媒体。","news",["国际新闻"],"中国","英文",False),
("timestamp","Timestamp Converter","https://www.epochconverter.com","时间戳转换。","utils",["开发工具"],"国际","英文",False),
("crontab","Crontab Guru","https://crontab.guru","Cron 表达式。","utils",["开发工具"],"国际","英文",False),
("jwt_io","JWT.io","https://jwt.io","JWT 解码。","utils",["开发工具"],"国际","英文",False),
("traefik","Traefik","https://traefik.io","反向代理。","ops",["Nginx"],"法国","英文",False),
("haproxy","HAProxy","https://www.haproxy.org","负载均衡。","ops",["Nginx"],"法国","英文",False),
("flstudio","FL Studio","https://www.image-line.com","音乐制作。","music",["音乐平台"],"比利时","英文",False),
("ableton","Ableton","https://www.ableton.com","音乐制作。","music",["音乐平台"],"德国","英文",False),
]
