# 第 B 批：开发/开源/数据库/运维
BATCHB = [
("stackoverflow","Stack Overflow","https://stackoverflow.com","程序员问答圣地。","dev",["编程社区"],"美国","英文",True),
("github_copilot_docs","GitHub Docs","https://docs.github.com","GitHub 官方文档。","dev",["技术文档"],"美国","英文",False),
("npm","npm","https://www.npmjs.com","JavaScript 包管理器。","dev",["包管理"],"美国","英文",False),
("pypi","PyPI","https://pypi.org","Python 包索引。","dev",["包管理"],"国际","英文",False),
("typescript","TypeScript","https://www.typescriptlang.org","JavaScript 的超集，类型安全。","dev",["编程语言"],"美国","英文",False),
("react","React","https://react.dev","Meta 的前端 UI 库。","dev",["开发框架"],"美国","英文",False),
("vue","Vue.js","https://vuejs.org","渐进式前端框架。","dev",["开发框架"],"国际","英文",False),
("nextjs","Next.js","https://nextjs.org","React 全栈框架。","dev",["开发框架"],"美国","英文",False),
("tailwind","Tailwind CSS","https://tailwindcss.com","实用优先的 CSS 框架。","dev",["开发框架"],"美国","英文",False),
("deno","Deno","https://deno.com","现代 JavaScript 运行时。","dev",["编程语言"],"国际","英文",False),
("jetbrains","JetBrains","https://www.jetbrains.com","专业 IDE 厂商（IDEA/PyCharm）。","dev",["IDE"],"捷克","英文",False),
("postman","Postman","https://www.postman.com","API 开发调试平台。","dev",["API平台"],"美国","英文",False),
("swagger","Swagger","https://swagger.io","API 设计文档工具。","dev",["API平台"],"美国","英文",False),
("git","Git","https://git-scm.com","分布式版本控制系统。","dev",["Git"],"国际","英文",False),
("codeberg","Codeberg","https://codeberg.org","非营利开源代码托管。","opensource",["代码托管","开源"],"德国","英文",False),
("sourceforge","SourceForge","https://sourceforge.net","老牌开源软件仓库。","opensource",["开源社区"],"美国","英文",False),
("opencollective","Open Collective","https://opencollective.com","开源项目资金管理。","opensource",["开源社区"],"美国","英文",False),
("fsf","自由软件基金会","https://www.fsf.org","FSF，自由软件运动。","opensource",["开源社区"],"美国","英文",False),
("apache","Apache 软件基金会","https://www.apache.org","顶级开源基金会。","opensource",["开源社区"],"美国","英文",False),
("sqlite","SQLite","https://www.sqlite.org","嵌入式关系数据库。","database",["数据库"],"美国","英文",False),
("mariadb","MariaDB","https://mariadb.org","MySQL 的开源分支。","database",["MySQL","开源"],"国际","英文",False),
("elasticsearch","Elasticsearch","https://www.elastic.co","分布式搜索分析引擎。","database",["数据库"],"美国","英文",False),
("supabase","Supabase","https://supabase.com","开源 Firebase 替代。","database",["数据库","开源"],"美国","英文",False),
("planetscale","PlanetScale","https://planetscale.com","Serverless MySQL 平台。","database",["MySQL"],"美国","英文",False),
("dbeaver","DBeaver","https://dbeaver.io","免费通用数据库工具。","database",["数据库工具"],"国际","英文",False),
("grafana","Grafana","https://grafana.com","开源监控可视化。","ops",["DevOps","开源"],"美国","英文",False),
("prometheus","Prometheus","https://prometheus.io","开源监控告警系统。","ops",["DevOps","开源"],"国际","英文",False),
("jenkins","Jenkins","https://www.jenkins.io","开源 CI/CD 自动化。","ops",["DevOps","开源"],"美国","英文",False),
("ansible","Ansible","https://www.ansible.com","自动化运维工具。","ops",["DevOps"],"美国","英文",False),
("terraform","Terraform","https://www.terraform.io","基础设施即代码。","ops",["DevOps"],"美国","英文",False),
("caddy","Caddy","https://caddyserver.com","自动 HTTPS 的 Web 服务器。","ops",["Nginx","开源"],"美国","英文",False),
("portainer","Portainer","https://www.portainer.io","容器可视化管理。","ops",["Docker"],"美国","英文",False),
("onepanel","1Panel","https://1panel.cn","国产开源服务器面板。","ops",["Linux","面板"],"中国","中文",False),
("linuxcn","Linux 中国","https://linux.cn","中文 Linux 社区。","ops",["Linux"],"中国","中文",False),
("digitalocean","DigitalOcean","https://www.digitalocean.com","开发者云服务器。","ops",["云服务器"],"美国","英文",False),
("linode","Linode","https://www.linode.com","老牌 VPS 服务商。","ops",["云服务器"],"美国","英文",False),
("bandwagon","搬瓦工","https://bandwagonhost.com","知名 VPS 服务商。","ops",["云服务器"],"美国","中文",False),
("ssl_labs","SSL Labs","https://www.ssllabs.com","SSL 配置检测。","nettools",["SSL检测"],"美国","英文",False),
("dnschecker","DNS Checker","https://dnschecker.org","全球 DNS 解析检测。","nettools",["DNS查询"],"国际","英文",False),
("ipchicken","IP 查询","https://www.ipchicken.com","查看本机公网 IP。","nettools",["IP查询"],"美国","英文",False),
]
