# 第 J 批：安全/系统/数据查询/天气/太空（目标各 15）
BATCHJ = [
# security 3->15 (+12)
("metasploit","Metasploit","https://www.metasploit.com","渗透测试框架。","security",["安全工具"],"美国","英文",False),
("burpsuite","Burp Suite","https://portswigger.net/burp","Web 安全测试平台。","security",["安全工具"],"英国","英文",False),
("nmap","Nmap","https://nmap.org","网络扫描工具。","security",["安全工具","开源"],"美国","英文",False),
("wireshark","Wireshark","https://www.wireshark.org","网络抓包分析。","security",["安全工具","开源"],"国际","英文",False),
("owasp","OWASP","https://owasp.org","Web 安全开放项目。","security",["安全工具"],"国际","英文",False),
("hackthebox","Hack The Box","https://www.hackthebox.com","渗透测试实训平台。","security",["安全工具"],"英国","英文",False),
("tryhackme","TryHackMe","https://tryhackme.com","网络安全学习平台。","security",["安全工具"],"英国","英文",False),
("vulnhub","VulnHub","https://www.vulnhub.com","靶机下载社区。","security",["安全工具"],"国际","英文",False),
("exploitdb","Exploit-DB","https://www.exploit-db.com","漏洞利用数据库。","security",["漏洞数据库"],"美国","英文",False),
("sans","SANS","https://www.sans.org","安全培训机构。","security",["安全工具"],"美国","英文",False),
("krebs","Krebs on Security","https://krebsonsecurity.com","知名安全博客。","security",["威胁情报"],"美国","英文",False),
("bleeping","BleepingComputer","https://www.bleepingcomputer.com","安全资讯站。","security",["威胁情报"],"美国","英文",False),
# os 3->15 (+12)
("mint","Linux Mint","https://linuxmint.com","易用的桌面发行版。","os",["Linux"],"爱尔兰","英文",False),
("opensuse","openSUSE","https://www.opensuse.org","社区发行版。","os",["Linux"],"德国","英文",False),
("elementary","elementary OS","https://elementary.io","美观的桌面系统。","os",["Linux"],"国际","英文",False),
("zorin","Zorin OS","https://zorin.com/os","Windows 风格 Linux。","os",["Linux"],"爱尔兰","英文",False),
("mxlinux","MX Linux","https://mxlinux.org","轻量稳定发行版。","os",["Linux"],"国际","英文",False),
("popos","Pop!_OS","https://pop.system76.com","System76 桌面系统。","os",["Linux"],"美国","英文",False),
("freebsd","FreeBSD","https://www.freebsd.org","BSD 操作系统。","os",["BSD"],"国际","英文",False),
("openbsd","OpenBSD","https://www.openbsd.org","安全著称的 BSD。","os",["BSD"],"加拿大","英文",False),
("haiku","Haiku","https://www.haiku-os.org","BeOS 兼容系统。","os",["Linux"],"国际","英文",False),
("reactos","ReactOS","https://reactos.org","开源 Windows 兼容。","os",["Windows","开源"],"国际","英文",False),
("gentoo","Gentoo","https://www.gentoo.org","源码编译发行版。","os",["Linux"],"国际","英文",False),
("alpine","Alpine Linux","https://alpinelinux.org","轻量安全发行版。","os",["Linux"],"国际","英文",False),
# dataquery 3->15 (+12)
("chinaz","站长之家","https://tool.chinaz.com","站长工具箱。","dataquery",["IP查询"],"中国","中文",False),
("aizhan","爱站网","https://www.aizhan.com","SEO 查询工具。","dataquery",["IP查询"],"中国","中文",False),
("mxtoolbox","MXToolbox","https://mxtoolbox.com","DNS/邮件检测。","dataquery",["DNS查询"],"美国","英文",False),
("viewdns","ViewDNS","https://viewdns.info","DNS 工具集。","dataquery",["DNS查询"],"国际","英文",False),
("robtex","Robtex","https://www.robtex.com","IP/DNS 综合查询。","dataquery",["IP查询"],"瑞典","英文",False),
("censys","Censys","https://censys.io","互联网资产搜索。","dataquery",["IP查询"],"美国","英文",False),
("fofa","FOFA","https://fofa.info","网络资产搜索引擎。","dataquery",["IP查询"],"中国","中文",False),
("quake","Quake 360","https://quake.360.cn","360 网络空间测绘。","dataquery",["IP查询"],"中国","中文",False),
("shodan2","Shodan 搜索","https://www.shodan.io","物联网搜索（补）。","dataquery",["IP查询"],"美国","英文",False),
("ipapi","ip-api","https://ip-api.com","免费 IP 查询 API。","dataquery",["IP查询"],"国际","英文",False),
("whatismyip","WhatIsMyIP","https://whatismyipaddress.com","IP 地址查询。","dataquery",["IP查询"],"美国","英文",False),
("yougetsignal","YouGetSignal","https://www.yougetsignal.com","网络工具集。","dataquery",["IP查询"],"美国","英文",False),
# weather 3->15 (+12)
("weathercom","Weather.com","https://weather.com","美国天气频道。","weather",["天气"],"美国","英文",False),
("wunderground","Weather Underground","https://www.wunderground.com","精准气象数据。","weather",["天气"],"美国","英文",False),
("meteoblue","meteoblue","https://www.meteoblue.com","瑞士气象服务。","weather",["天气"],"瑞士","英文",False),
("yrno","Yr.no","https://www.yr.no","挪威气象局。","weather",["天气"],"挪威","英文",False),
("ventusky","Ventusky","https://www.ventusky.com","气象可视化地图。","weather",["天气"],"捷克","英文",False),
("tropicaltidbits","Tropical Tidbits","https://www.tropicaltidbits.com","热带气旋分析。","weather",["台风"],"美国","英文",False),
("jma","日本气象厅","https://www.jma.go.jp","日本官方气象。","weather",["天气"],"日本","日文",False),
("cwa","中央气象署","https://www.cwa.gov.tw","台湾气象。","weather",["台风"],"中国台湾","中文",False),
("usgs_quake","USGS 地震","https://earthquake.usgs.gov","美国地质调查局地震。","weather",["地震"],"美国","英文",False),
("nhc","美国飓风中心","https://www.nhc.noaa.gov","NOAA 飓风预报。","weather",["台风"],"美国","英文",False),
("weatherbug","WeatherBug","https://www.weatherbug.com","天气应用。","weather",["天气"],"美国","英文",False),
("climatempo","ClimaCell","https://www.tomorrow.io","明日气象 API。","weather",["天气"],"美国","英文",False),
# space 3->15 (+12)
("esa","欧空局 ESA","https://www.esa.int","欧洲航天局。","space",["NASA"],"法国","英文",False),
("jaxa","JAXA","https://www.jaxa.jp","日本宇宙航空机构。","space",["NASA"],"日本","英文",False),
("spacecom","Space.com","https://www.space.com","太空新闻。","space",["NASA"],"美国","英文",False),
("universetoday","Universe Today","https://www.universetoday.com","天文资讯。","space",["天文观测"],"美国","英文",False),
("heavensabove","Heavens-Above","https://www.heavens-above.com","卫星过境预报。","space",["卫星追踪"],"德国","英文",False),
("stellarium","Stellarium","https://stellarium.org","免费星空模拟。","space",["天文观测","开源"],"国际","英文",False),
("inthesky","In-The-Sky","https://in-the-sky.org","天文历与星图。","space",["天文观测"],"英国","英文",False),
("lightpollution","光污染地图","https://www.lightpollutionmap.info","光污染查询。","space",["天文观测"],"国际","英文",False),
("iss_tracker","ISS 追踪","https://isstracker.pl","国际空间站实时追踪。","space",["卫星追踪"],"波兰","英文",False),
("planet4589","Planet 4589","https://planet4589.org","卫星数据库。","space",["卫星追踪"],"美国","英文",False),
("spaceweather","SpaceWeather","https://spaceweather.com","空间天气。","space",["NASA"],"美国","英文",False),
("cnsa","国家航天局","https://www.cnsa.gov.cn","中国国家航天局。","space",["NASA"],"中国","中文",False),
]
