# 第 N 批：邮箱/健康/开源/物流（目标各 24）
BATCHN = [
# email 8->24 (+16)
("yahoo_mail","Yahoo Mail","https://mail.yahoo.com","雅虎邮箱。","email",["免费邮箱"],"美国","英文",False),
("aol_mail","AOL Mail","https://mail.aol.com","AOL 邮箱。","email",["免费邮箱"],"美国","英文",False),
("gmx","GMX","https://www.gmx.com","德国免费邮箱。","email",["免费邮箱"],"德国","英文",False),
("zoho_mail","Zoho Mail","https://www.zoho.com/mail","Zoho 邮箱。","email",["免费邮箱"],"印度","英文",False),
("fastmail","Fastmail","https://www.fastmail.com","付费隐私邮箱。","email",["免费邮箱"],"澳大利亚","英文",False),
("hey","HEY","https://www.hey.com","Basecamp 邮箱。","email",["免费邮箱"],"美国","英文",False),
("mailcom","mail.com","https://www.mail.com","免费邮箱。","email",["免费邮箱"],"德国","英文",False),
("yandex_mail","Yandex Mail","https://mail.yandex.com","Yandex 邮箱。","email",["免费邮箱"],"俄罗斯","英文",False),
("naver_mail","Naver Mail","https://mail.naver.com","韩国邮箱。","email",["免费邮箱"],"韩国","韩文",False),
("daum_mail","Daum 邮箱","https://mail.daum.net","韩国邮箱。","email",["免费邮箱"],"韩国","韩文",False),
("aliyun_mail","阿里云邮箱","https://mail.aliyun.com","企业邮箱。","email",["企业邮箱"],"中国","中文",False),
("exmail","腾讯企业邮","https://exmail.qq.com","企业邮箱。","email",["企业邮箱"],"中国","中文",False),
# health 8->24 (+16)
("clevelandclinic","Cleveland Clinic","https://my.clevelandclinic.org","克利夫兰诊所。","health",["医疗机构"],"美国","英文",False),
("johnshopkins","约翰霍普金斯","https://www.hopkinsmedicine.org","医学院。","health",["医疗机构"],"美国","英文",False),
("nhs","NHS","https://www.nhs.uk","英国医疗服务。","health",["医疗机构"],"英国","英文",False),
("medlineplus","MedlinePlus","https://medlineplus.gov","医学百科。","health",["医学资源"],"美国","英文",False),
("uptodate","UpToDate","https://www.uptodate.com","临床决策。","health",["医学资源"],"美国","英文",False),
("medscape","Medscape","https://www.medscape.com","医学资讯。","health",["医学资源"],"美国","英文",False),
("lancet","柳叶刀","https://www.thelancet.com","顶级医学期刊。","health",["医学资源"],"英国","英文",False),
("bmj","BMJ","https://www.bmj.com","英国医学期刊。","health",["医学资源"],"英国","英文",False),
("jama","JAMA","https://jamanetwork.com","美国医学会期刊。","health",["医学资源"],"美国","英文",False),
("cdc","美国CDC","https://www.cdc.gov","疾控中心。","health",["医疗机构"],"美国","英文",False),
("phec","中国疾控中心","https://www.chinacdc.cn","疾控中心。","health",["医疗机构"],"中国","中文",False),
("nhc_gov","国家卫健委","https://www.nhc.gov.cn","卫健委。","health",["医疗机构"],"中国","中文",False),
("medlive","医脉通","https://www.medlive.cn","医学资讯。","health",["医学资源"],"中国","中文",False),
("yimaihui","e医汇","https://www.yimaihui.com","医学会议。","health",["医学资源"],"中国","中文",False),
# opensource 9->24 (+15)
("sourcehut","SourceHut","https://sourcehut.org","黑客代码托管。","opensource",["代码托管"],"国际","英文",False),
("notabug","NotABug","https://notabug.org","自由软件托管。","opensource",["代码托管"],"国际","英文",False),
("radicle","Radicle","https://radicle.xyz","去中心化代码协作。","opensource",["代码托管"],"国际","英文",False),
("oschina","开源中国","https://www.oschina.net","中文开源社区。","opensource",["开源社区"],"中国","中文",False),
("hellogithub","HelloGitHub","https://hellogithub.com","开源项目月刊。","opensource",["开源社区"],"中国","中文",False),
("opensource_guide","开源指南","https://opensource.guide","GitHub 开源指南。","opensource",["开源社区"],"美国","英文",False),
("choosealicense","Choose a License","https://choosealicense.com","许可证选择。","opensource",["开源社区"],"美国","英文",False),
("librariesio","Libraries.io","https://libraries.io","开源包搜索。","opensource",["开源社区"],"国际","英文",False),
("npmmirror","npmmirror","https://npmmirror.com","淘宝 NPM 镜像。","opensource",["开源社区"],"中国","中文",False),
("gitpod","Gitpod","https://www.gitpod.io","云端开发环境。","opensource",["代码托管"],"德国","英文",False),
("codesandbox","CodeSandbox","https://codesandbox.io","在线代码沙盒。","opensource",["代码托管"],"荷兰","英文",False),
("stackblitz","StackBlitz","https://stackblitz.com","在线 IDE。","opensource",["代码托管"],"美国","英文",False),
# logistics 9->24 (+15)
("tnt","TNT","https://www.tnt.com","国际快递。","logistics",["国际快递"],"荷兰","英文",False),
("aramex","Aramex","https://www.aramex.com","中东快递。","logistics",["国际快递"],"阿联酋","英文",False),
("yodel","Yodel","https://www.yodel.co.uk","英国快递。","logistics",["国际快递"],"英国","英文",False),
("dpd","DPD","https://www.dpd.com","欧洲快递。","logistics",["国际快递"],"法国","英文",False),
("gls","GLS","https://gls-group.com","欧洲快递。","logistics",["国际快递"],"荷兰","英文",False),
("yamato","雅玛多","https://www.kuronekoyamato.co.jp","日本快递。","logistics",["国际快递"],"日本","日文",False),
("sagawa","佐川急便","https://www.sagawa-exp.co.jp","日本快递。","logistics",["国际快递"],"日本","日文",False),
("cj_logistics","CJ 大韩通运","https://www.cjlogistics.com","韩国物流。","logistics",["国际快递"],"韩国","英文",False),
("msc","地中海航运","https://www.msc.com","集装箱航运。","logistics",["海运"],"瑞士","英文",False),
("cma_cgm","达飞轮船","https://www.cma-cgm.com","法国航运。","logistics",["海运"],"法国","英文",False),
("hapag","赫伯罗特","https://www.hapag-lloyd.com","德国航运。","logistics",["海运"],"德国","英文",False),
("evergreen","长荣海运","https://www.evergreen-line.com","台湾航运。","logistics",["海运"],"中国台湾","英文",False),
("one_line","ONE","https://www.one-line.com","海洋网联。","logistics",["海运"],"新加坡","英文",False),
("zim","以星航运","https://www.zim.com","以色列航运。","logistics",["海运"],"以色列","英文",False),
("kuehne","德迅","https://www.kuehne-nagel.com","货代巨头。","logistics",["海运"],"瑞士","英文",False),
("dsf_logistics","DSV","https://www.dsv.com","丹麦货代。","logistics",["海运"],"丹麦","英文",False),
("xpo","XPO Logistics","https://www.xpo.com","美国物流。","logistics",["海运"],"美国","英文",False),
("jb_hunt","J.B. Hunt","https://www.jbhunt.com","美国货运。","logistics",["海运"],"美国","英文",False),
("old_dominion","Old Dominion","https://www.odfl.com","零担货运。","logistics",["海运"],"美国","英文",False),
("yrc","YRC","https://yrc.com","货运公司。","logistics",["海运"],"美国","英文",False),
("panalpina","Panalpina","https://www.panalpina.com","货代。","logistics",["海运"],"瑞士","英文",False),
("hellmann","Hellmann","https://www.hellmann.com","德国货代。","logistics",["海运"],"德国","英文",False),
]
