# 第 L 批：网络工具/苹果/政府/企业/翻译（目标各 15-18）
BATCHL = [
# nettools 6->18 (+12)
("pingdom","Pingdom","https://www.pingdom.com","网站监控。","nettools",["网速测试"],"美国","英文",False),
("gtmetrix","GTmetrix","https://gtmetrix.com","网站速度分析。","nettools",["网速测试"],"加拿大","英文",False),
("webpagetest","WebPageTest","https://www.webpagetest.org","性能测试。","nettools",["网速测试"],"美国","英文",False),
("isitwp","IsItWP","https://www.isitwp.com","WordPress 检测。","nettools",["DNS查询"],"美国","英文",False),
("builtwith","BuiltWith","https://builtwith.com","网站技术栈查询。","nettools",["DNS查询"],"美国","英文",False),
("wappalyzer","Wappalyzer","https://www.wappalyzer.com","技术栈识别。","nettools",["DNS查询"],"澳大利亚","英文",False),
("securityheaders","Security Headers","https://securityheaders.com","HTTP 安全头检测。","nettools",["SSL检测"],"英国","英文",False),
("hardenize","Hardenize","https://www.hardenize.com","安全配置检测。","nettools",["SSL检测"],"英国","英文",False),
("urlscan","urlscan.io","https://urlscan.io","URL 安全扫描。","nettools",["SSL检测"],"丹麦","英文",False),
("bgpview","BGPView","https://bgpview.io","BGP 路由查询。","nettools",["DNS查询"],"国际","英文",False),
# apple 6->18 (+12)
("iphone","iPhone","https://www.apple.com/iphone","苹果手机。","apple",["iOS"],"美国","英文",False),
("mac","Mac","https://www.apple.com/mac","苹果电脑。","apple",["macOS"],"美国","英文",False),
("ipad","iPad","https://www.apple.com/ipad","苹果平板。","apple",["iOS"],"美国","英文",False),
("appstore","App Store","https://www.apple.com/app-store","应用商店。","apple",["iOS"],"美国","英文",False),
("testflight","TestFlight","https://developer.apple.com/testflight","测试分发。","apple",["iOS"],"美国","英文",False),
("swift","Swift","https://www.swift.org","苹果编程语言。","apple",["iOS"],"美国","英文",False),
("appleinsider","AppleInsider","https://appleinsider.com","苹果新闻。","apple",["iOS"],"美国","英文",False),
("cultofmac","Cult of Mac","https://www.cultofmac.com","苹果媒体。","apple",["macOS"],"美国","英文",False),
("imazing","iMazing","https://imazing.com","iOS 设备管理。","apple",["iOS"],"瑞士","英文",False),
("altstore","AltStore","https://altstore.io","第三方应用商店。","apple",["iOS"],"美国","英文",False),
("sideloadly","Sideloadly","https://sideloadly.io","侧载工具。","apple",["iOS"],"国际","英文",False),
# gov 6->18 (+12)
("congress","美国国会","https://www.congress.gov","国会官网。","gov",["美国政府"],"美国","英文",False),
("senate","美国参议院","https://www.senate.gov","参议院。","gov",["美国政府"],"美国","英文",False),
("state_gov","美国国务院","https://www.state.gov","国务院。","gov",["美国政府"],"美国","英文",False),
("loc","美国国会图书馆","https://www.loc.gov","国会图书馆。","gov",["美国政府"],"美国","英文",False),
("archives","美国档案馆","https://www.archives.gov","国家档案。","gov",["美国政府"],"美国","英文",False),
("npc","全国人大","https://www.npc.gov.cn","人大官网。","gov",["中国政府"],"中国","中文",False),
("cppcc","全国政协","https://www.cppcc.gov.cn","政协官网。","gov",["中国政府"],"中国","中文",False),
("mfa","外交部","https://www.mfa.gov.cn","中国外交部。","gov",["中国政府"],"中国","中文",False),
("europa2","欧盟委员会","https://commission.europa.eu","欧盟委员会。","gov",["欧盟机构"],"比利时","英文",False),
# companies 6->18 (+12)
("pitchbook","PitchBook","https://pitchbook.com","私募创投数据。","companies",["科技企业"],"美国","英文",False),
("tracxn","Tracxn","https://tracxn.com","创业公司数据库。","companies",["科技企业"],"印度","英文",False),
("owler","Owler","https://www.owler.com","企业情报。","companies",["科技企业"],"美国","英文",False),
("signalhire","SignalHire","https://www.signalhire.com","企业联系人。","companies",["科技企业"],"美国","英文",False),
("apollo","Apollo.io","https://www.apollo.io","销售情报。","companies",["科技企业"],"美国","英文",False),
("zoominfo","ZoomInfo","https://www.zoominfo.com","B2B 数据库。","companies",["科技企业"],"美国","英文",False),
("dnb","Dun & Bradstreet","https://www.dnb.com","企业征信。","companies",["科技企业"],"美国","英文",False),
("hoovers","Hoovers","https://www.hoovers.com","企业名录。","companies",["科技企业"],"美国","英文",False),
("bloomberg_co","Bloomberg 公司","https://www.bloomberg.com/company","彭博公司。","companies",["科技企业"],"美国","英文",False),
# translate 5->17 (+12)
("reverso","Reverso","https://www.reverso.net","语境翻译。","translate",["在线翻译"],"法国","多语言",False),
("linguee","Linguee","https://www.linguee.com","双语词典。","translate",["在线翻译"],"德国","多语言",False),
("glosbe","Glosbe","https://glosbe.com","多语言词典。","translate",["在线翻译"],"波兰","多语言",False),
("wordreference","WordReference","https://www.wordreference.com","词典论坛。","translate",["在线翻译"],"美国","多语言",False),
("dict_cc","dict.cc","https://www.dict.cc","德英词典。","translate",["在线翻译"],"奥地利","多语言",False),
("jisho","Jisho","https://jisho.org","日英词典。","translate",["在线翻译"],"国际","英文",False),
("weblio","Weblio","https://www.weblio.jp","日语词典。","translate",["在线翻译"],"日本","日文",False),
("naver_dict","Naver 词典","https://dict.naver.com","韩语词典。","translate",["在线翻译"],"韩国","韩文",False),
("papago","Papago","https://papago.naver.com","Naver 翻译。","translate",["在线翻译"],"韩国","多语言",False),
("yandex_translate","Yandex 翻译","https://translate.yandex.com","Yandex 翻译。","translate",["在线翻译"],"俄罗斯","多语言",False),
("libretranslate","LibreTranslate","https://libretranslate.com","开源翻译。","translate",["在线翻译","开源"],"国际","多语言",False),
("argostranslate","Argos Translate","https://www.argosopentech.com","开源翻译引擎。","translate",["在线翻译","开源"],"美国","英文",False),
("crowdin","Crowdin","https://crowdin.com","本地化平台。","translate",["在线翻译"],"乌克兰","英文",False),
("transifex","Transifex","https://www.transifex.com","翻译管理。","translate",["在线翻译"],"美国","英文",False),
("smartling","Smartling","https://www.smartling.com","企业翻译。","translate",["在线翻译"],"美国","英文",False),
("gengo","Gengo","https://gengo.com","人工翻译。","translate",["在线翻译"],"日本","英文",False),
("onehour","One Hour Translation","https://www.onehourtranslation.com","快速翻译。","translate",["在线翻译"],"美国","英文",False),
("netflix_jobs","Netflix Jobs","https://jobs.netflix.com","Netflix 招聘。","companies",["科技企业"],"美国","英文",False),
("ycombinator_co","Y Combinator","https://www.ycombinator.com","创业孵化器。","companies",["科技企业"],"美国","英文",False),
("techcrunch_co","TechCrunch 公司","https://techcrunch.com","科技媒体（补）。","companies",["科技企业"],"美国","英文",False),
("whitehouse2","白宫官网","https://www.whitehouse.gov","白宫（补）。","gov",["美国政府"],"美国","英文",False),
]
